import 'package:flutter/material.dart';
import '../../../core/utils/icon_utils.dart';
import '../../../l10n/app_localizations.dart';

class TransactionCategoryData {
  /// Özel alt kategorileri built-in kategori listesine merge eder.
  /// Her özel alt kategori, parent kategorisinin ikonunu kullanır.
  /// [categories] — Built-in kategori listesi (deep copy yapılır, orijinal değişmez)
  /// [customSubs] — CustomCategoryService'den gelen özel alt kategoriler
  static List<Map<String, dynamic>> mergeCustomSubcategories(
    List<Map<String, dynamic>> categories,
    List<Map<String, String>> customSubs,
  ) {
    if (customSubs.isEmpty) return categories;

    // Deep copy: orijinal listeyi bozmamak için
    final merged = categories.map((cat) {
      final copy = Map<String, dynamic>.from(cat);
      copy['subModels'] = List<Map<String, dynamic>>.from(
        (cat['subModels'] as List).map((s) => Map<String, dynamic>.from(s)),
      );
      return copy;
    }).toList();

    for (final custom in customSubs) {
      final parentId = custom['parentId'] ?? '';
      final parentIndex = merged.indexWhere((c) => c['id'] == parentId);
      if (parentIndex == -1) continue;

      final parent = merged[parentIndex];
      final subs = parent['subModels'] as List<Map<String, dynamic>>;

      // Zaten eklenmişse tekrar ekleme
      if (subs.any((s) => s['id'] == custom['id'])) continue;

      final int? iconCode = int.tryParse(custom['iconCode'] ?? '');
      subs.add({
        'id': custom['id'] ?? '',
        'name': custom['name'] ?? '',
        'icon': iconCode != null 
            ? IconData(iconCode, fontFamily: 'MaterialIcons') 
            : parent['icon'] as IconData, 
        'isCustom': true,
      });
    }

    return merged;
  }

  static String? _getL10nCategoryName(AppLocalizations l10n, String id) {
    switch (id) {
      case 'exp_rent': return l10n.rent;
      case 'exp_rent_office': return l10n.office;
      case 'exp_rent_storage': return l10n.storage;
      case 'exp_bill': return l10n.bill;
      case 'exp_bill_electricity': return l10n.electricity;
      case 'exp_bill_water': return l10n.water;
      case 'exp_bill_gas': return l10n.gas;
      case 'exp_bill_internet': return l10n.internet;
      case 'exp_bill_phone': return l10n.phone;
      case 'exp_grocery': return l10n.grocery;
      case 'exp_grocery_food': return l10n.food;
      case 'exp_grocery_cleaning': return l10n.cleaning;
      case 'exp_dining': return l10n.dining;
      case 'exp_dining_restaurant': return l10n.restaurant;
      case 'exp_dining_cafe': return l10n.cafe;
      case 'exp_dining_delivery': return l10n.delivery;
      case 'exp_health': return l10n.health;
      case 'exp_health_doctor': return l10n.doctor;
      case 'exp_health_medicine': return l10n.medicine;
      case 'exp_health_surgery': return l10n.surgery;
      case 'exp_health_dentist': return l10n.dentist;
      case 'exp_trans_taxi': return l10n.taxi;
      case 'exp_trans_bus': return l10n.bus;
      case 'exp_car_fuel': return l10n.fuel;
      case 'exp_cloth_shoes': return l10n.shoes;
      case 'inc_salary': return l10n.salary;
      case 'inc_salary_bonus': return l10n.bonus;
      case 'inc_salary_dividend': return l10n.dividend;
      case 'inc_extra_freelance': return l10n.freelance;
      case 'inc_extra_commission': return l10n.commission;
      case 'inc_invest_stock': return l10n.stock;
      case 'inc_invest_crypto': return l10n.crypto;
      case 'inc_invest_interest': return l10n.interest;
      case 'inc_rent': return l10n.rent;
      case 'inc_scholarship': return l10n.scholarship;
      case 'inc_sale': return l10n.sale;
      case 'inc_gift': return l10n.gift;
      case 'exp_other': return l10n.other;
      default: return null;
    }
  }

  static String getCategoryName(BuildContext context, String id) {
    final locale = Localizations.localeOf(context).languageCode;
    
    // 1. Try resolving using AppLocalizations first
    final l10n = AppLocalizations.of(context);
    if (l10n != null) {
      final l10nName = _getL10nCategoryName(l10n, id);
      if (l10nName != null) {
        return l10nName;
      }
    }
    
    final Map<String, Map<String, String>> names = {
      // ==========================================
      // GİDERLER (EXPENSES)
      // ==========================================
      // Barınma
      'exp_rent': {
        'tr': 'Barınma',
        'en': 'Housing',
        'de': 'Wohnen',
        'es': 'Vivienda',
        'fr': 'Logement',
        'it': 'Abitazione',
        'ja': '住居',
        'ko': '주거',
        'pt': 'Habitação',
        'zh': '住房',
      },
      'exp_rent_home': {
        'tr': 'Ev Kirası',
        'en': 'Home Rent',
        'de': 'Hausmiete',
        'es': 'Alquiler de vivienda',
        'fr': 'Loyer de maison',
        'it': 'Affitto casa',
        'ja': '家賃',
        'ko': '주택 월세',
        'pt': 'Aluguel de casa',
        'zh': '房租',
      },
      'exp_rent_office': {
        'tr': 'Ofis Kirası',
        'en': 'Office Rent',
        'de': 'Büromiete',
        'es': 'Alquiler de oficina',
        'fr': 'Loyer de bureau',
        'it': 'Affitto ufficio',
        'ja': 'オフィス賃料',
        'ko': '사무실 임대료',
        'pt': 'Aluguel de escritório',
        'zh': '办公室租金',
      },
      'exp_rent_mortgage': {
        'tr': 'Konut Kredisi',
        'en': 'Mortgage',
        'de': 'Hypothek',
        'es': 'Hipoteca',
        'fr': 'Hypothèque',
        'it': 'Mutuo',
        'ja': '住宅ローン',
        'ko': '주택 담보 대출',
        'pt': 'Hipoteca',
        'zh': '房屋貸款',
      },
      'exp_rent_maintenance': {
        'tr': 'Tadilat',
        'en': 'Maintenance',
        'de': 'Instandhaltung',
        'es': 'Mantenimiento',
        'fr': 'Entretien',
        'it': 'Manutenzione',
        'ja': 'メンテナンス',
        'ko': '유지 보수',
        'pt': 'Manutenção',
        'zh': '房屋维护',
      },
      'exp_rent_storage': {
        'tr': 'Depolama',
        'en': 'Storage',
        'de': 'Lagerung',
        'es': 'Almacenamiento',
        'fr': 'Stockage',
        'it': 'Deposito',
        'ja': '保管・倉庫',
        'ko': '보관소',
        'pt': 'Armazenamento',
        'zh': '仓储',
      },
      'exp_rent_insurance': {
        'tr': 'Konut Sigortası',
        'en': 'Home Insurance',
        'de': 'Hausversicherung',
        'es': 'Seguro de hogar',
        'fr': 'Assurance habitation',
        'it': 'Assicurazione casa',
        'ja': '火災・住宅保険',
        'ko': '주택 보험',
        'pt': 'Seguro residencial',
        'zh': '房屋保险',
      },
      'exp_rent_moving': {
        'tr': 'Taşınma',
        'en': 'Moving',
        'de': 'Umzug',
        'es': 'Mudanza',
        'fr': 'Déménagement',
        'it': 'Trasloco',
        'ja': '引っ越し',
        'ko': '이사',
        'pt': 'Mudança',
        'zh': '搬家',
      },
      'exp_rent_dorm': {
        'tr': 'Yurt',
        'en': 'Dormitory',
        'de': 'Wohnheim',
        'es': 'Residencia estudiantil',
        'fr': 'Dortoir',
        'it': 'Dormitorio',
        'ja': '寮',
        'ko': '기숙사',
        'pt': 'Dormitório',
        'zh': '宿舍',
      },
      'exp_rent_room': {
        'tr': 'Oda Kirası',
        'en': 'Room Rent',
        'de': 'Zimmer-Miete',
        'es': 'Alquiler de habitación',
        'fr': 'Loyer de chambre',
        'it': 'Affitto camera',
        'ja': 'ルームシェア・部屋代',
        'ko': '방 임대료',
        'pt': 'Aluguel de quarto',
        'zh': '房租(单间)',
      },
      
      // Faturalar
      'exp_bill': {
        'tr': 'Faturalar',
        'en': 'Bills',
        'de': 'Rechnungen',
        'es': 'Facturas',
        'fr': 'Factures',
        'it': 'Bollette',
        'ja': '請求書・公共料金',
        'ko': '공공요금',
        'pt': 'Contas',
        'zh': '账单',
      },
      'exp_bill_electricity': {
        'tr': 'Elektrik',
        'en': 'Electricity',
        'de': 'Strom',
        'es': 'Electricidad',
        'fr': 'Électricité',
        'it': 'Elettricità',
        'ja': '電気代',
        'ko': '전기 요금',
        'pt': 'Eletricidade',
        'zh': '电费',
      },
      'exp_bill_water': {
        'tr': 'Su',
        'en': 'Water',
        'de': 'Wasser',
        'es': 'Agua',
        'fr': 'Eau',
        'it': 'Acqua',
        'ja': '水道代',
        'ko': '수도 요금',
        'pt': 'Água',
        'zh': '水费',
      },
      'exp_bill_gas': {
        'tr': 'Doğalgaz',
        'en': 'Gas',
        'de': 'Gas',
        'es': 'Gas',
        'fr': 'Gaz',
        'it': 'Gas',
        'ja': 'ガス代',
        'ko': '가스 요금',
        'pt': 'Gás',
        'zh': '燃气费',
      },
      'exp_bill_internet': {
        'tr': 'İnternet',
        'en': 'Internet',
        'de': 'Internet',
        'es': 'Internet',
        'fr': 'Internet',
        'it': 'Internet',
        'ja': 'インターネット代',
        'ko': '인터넷',
        'pt': 'Internet',
        'zh': '宽带费',
      },
      'exp_bill_phone': {
        'tr': 'Telefon',
        'en': 'Phone',
        'de': 'Telefon',
        'es': 'Teléfono',
        'fr': 'Téléphone',
        'it': 'Telefono',
        'ja': '電話代',
        'ko': '전화 요금',
        'pt': 'Telefone',
        'zh': '电话费',
      },
      'exp_bill_dues': {
        'tr': 'Aidat',
        'en': 'Dues',
        'de': 'Gebühren',
        'es': 'Cuotas',
        'fr': 'Cotisations',
        'it': 'Spese condominiali',
        'ja': '会費・管理費',
        'ko': '관리비',
        'pt': 'Condomínio',
        'zh': '物业费',
      },
      'exp_bill_tv': {
        'tr': 'Televizyon',
        'en': 'TV',
        'de': 'Fernsehen',
        'es': 'TV',
        'fr': 'Télévision',
        'it': 'TV',
        'ja': 'テレビ代',
        'ko': 'TV 요금',
        'pt': 'TV',
        'zh': '电视费',
      },
      
      // Market
      'exp_grocery': {
        'tr': 'Market',
        'en': 'Grocery',
        'de': 'Lebensmittel',
        'es': 'Supermercado',
        'fr': 'Épicerie',
        'it': 'Spesa',
        'ja': '食料品・日用品',
        'ko': '식료품',
        'pt': 'Supermercado',
        'zh': '超市百货',
      },
      'exp_grocery_food': {
        'tr': 'Gıda',
        'en': 'Food',
        'de': 'Essen',
        'es': 'Comida',
        'fr': 'Nourriture',
        'it': 'Cibo',
        'ja': '食品',
        'ko': '식품',
        'pt': 'Alimentação',
        'zh': '食品',
      },
      'exp_grocery_cleaning': {
        'tr': 'Temizlik',
        'en': 'Cleaning',
        'de': 'Reinigung',
        'es': 'Limpieza',
        'fr': 'Nettoyage',
        'it': 'Pulizia',
        'ja': '掃除用品',
        'ko': '청소 용품',
        'pt': 'Limpeza',
        'zh': '清洁用品',
      },
      'exp_grocery_drink': {
        'tr': 'İçecek',
        'en': 'Drink',
        'de': 'Getränke',
        'es': 'Bebidas',
        'fr': 'Boissons',
        'it': 'Bevande',
        'ja': '飲料',
        'ko': '음료',
        'pt': 'Bebidas',
        'zh': '饮料',
      },
      'exp_grocery_pet': {
        'tr': 'Evcil Hayvan',
        'en': 'Pet Care',
        'de': 'Haustierpflege',
        'es': 'Cuidado de mascotas',
        'fr': 'Soins des animaux',
        'it': 'Cura degli animali',
        'ja': 'ペット用品',
        'ko': '반려동물 케어',
        'pt': 'Pet care',
        'zh': '宠物用品',
      },
      'exp_grocery_hygiene': {
        'tr': 'Kişisel Hijyen',
        'en': 'Personal Hygiene',
        'de': 'Körperpflege',
        'es': 'Higiene personal',
        'fr': 'Hygiène personnelle',
        'it': 'Igiene personale',
        'ja': '衛生用品',
        'ko': '개인 위생',
        'pt': 'Higiene pessoal',
        'zh': '个人卫生',
      },
      'exp_grocery_tobacco': {
        'tr': 'Tütün',
        'en': 'Tobacco',
        'de': 'Tabak',
        'es': 'Tabaco',
        'fr': 'Tabac',
        'it': 'Tabacco',
        'ja': 'タバコ',
        'ko': '담배',
        'pt': 'Tabaco',
        'zh': '烟草',
      },
      'exp_grocery_alcohol': {
        'tr': 'Alkol',
        'en': 'Alcohol',
        'de': 'Alkohol',
        'es': 'Alcohol',
        'fr': 'Alcool',
        'it': 'Alcol',
        'ja': 'お酒',
        'ko': '주류',
        'pt': 'Álcool',
        'zh': '酒类',
      },
      
      // Yemek
      'exp_dining': {
        'tr': 'Yemek',
        'en': 'Dining',
        'de': 'Restaurantbesuche',
        'es': 'Restaurantes',
        'fr': 'Restauration',
        'it': 'Ristorazione',
        'ja': '外食',
        'ko': '외식',
        'pt': 'Restaurantes',
        'zh': '餐饮外食',
      },
      'exp_dining_restaurant': {
        'tr': 'Restoran',
        'en': 'Restaurant',
        'de': 'Restaurant',
        'es': 'Restaurante',
        'fr': 'Restaurant',
        'it': 'Ristorante',
        'ja': 'レストラン',
        'ko': '레스토랑',
        'pt': 'Restaurante',
        'zh': '餐厅',
      },
      'exp_dining_cafe': {
        'tr': 'Kafe',
        'en': 'Cafe',
        'de': 'Café',
        'es': 'Cafetería',
        'fr': 'Café',
        'it': 'Caffè',
        'ja': 'カフェ',
        'ko': '카페',
        'pt': 'Café',
        'zh': '咖啡厅',
      },
      'exp_dining_fastfood': {
        'tr': 'Hızlı Yemek',
        'en': 'Fast Food',
        'de': 'Fast Food',
        'es': 'Comida rápida',
        'fr': 'Fast-food',
        'it': 'Fast food',
        'ja': 'ファストフード',
        'ko': '패스트푸드',
        'pt': 'Fast food',
        'zh': '快餐',
      },
      'exp_dining_delivery': {
        'tr': 'Eve Sipariş',
        'en': 'Delivery',
        'de': 'Lieferung',
        'es': 'Domicilio',
        'fr': 'Livraison',
        'it': 'Consegna',
        'ja': 'デリバリー',
        'ko': '배달',
        'pt': 'Delivery',
        'zh': '外卖',
      },
      'exp_dining_canteen': {
        'tr': 'Kantin',
        'en': 'Canteen',
        'de': 'Kantine',
        'es': 'Cantina',
        'fr': 'Cantine',
        'it': 'Mensa',
        'ja': '食堂・売店',
        'ko': '매점',
        'pt': 'Cantina',
        'zh': '食堂',
      },
      
      // Ulaşım
      'exp_trans': {
        'tr': 'Ulaşım',
        'en': 'Transportation',
        'de': 'Transport',
        'es': 'Transporte',
        'fr': 'Transport',
        'it': 'Trasporti',
        'ja': '交通機関',
        'ko': '교통',
        'pt': 'Transporte',
        'zh': '交通出行',
      },
      'exp_trans_bus': {
        'tr': 'Toplu Taşıma',
        'en': 'Public Transit',
        'de': 'Öffentlicher Nahverkehr',
        'es': 'Transporte público',
        'fr': 'Transport en commun',
        'it': 'Trasporti pubblici',
        'ja': '公共交通機関',
        'ko': '대중교통',
        'pt': 'Transporte público',
        'zh': '公共交通',
      },
      'exp_trans_taxi': {
        'tr': 'Taksi',
        'en': 'Taxi',
        'de': 'Taxi',
        'es': 'Taxi',
        'fr': 'Taxi',
        'it': 'Taxi',
        'ja': 'タクシー',
        'ko': '택시',
        'pt': 'Táxi',
        'zh': '出租车',
      },
      'exp_trans_intercity': {
        'tr': 'Şehirlerarası Ulaşım',
        'en': 'Intercity Transit',
        'de': 'Fernverkehr',
        'es': 'Transporte interurbano',
        'fr': 'Transport interurbain',
        'it': 'Trasporti interurbani',
        'ja': '長距離交通',
        'ko': '시외 교통',
        'pt': 'Viagem intermunicipal',
        'zh': '城际交通',
      },
      'exp_trans_scooter': {
        'tr': 'Mikromobilite',
        'en': 'Micromobility',
        'de': 'Mikromobilität',
        'es': 'Micromovilidad',
        'fr': 'Micromobilité',
        'it': 'Micromobilità',
        'ja': 'マイクロモビリティ',
        'ko': '마이크로 모빌리티',
        'pt': 'Micromobilidade',
        'zh': '共享单车/滑板车',
      },
      
      // Araç
      'exp_car': {
        'tr': 'Araç',
        'en': 'Vehicle',
        'de': 'Fahrzeug',
        'es': 'Vehículo',
        'fr': 'Véhicule',
        'it': 'Veicolo',
        'ja': '車・乗り物',
        'ko': '차량',
        'pt': 'Veículo',
        'zh': '车辆',
      },
      'exp_car_fuel': {
        'tr': 'Akaryakıt',
        'en': 'Fuel',
        'de': 'Kraftstoff',
        'es': 'Combustible',
        'fr': 'Carburant',
        'it': 'Carburante',
        'ja': 'ガソリン・燃料',
        'ko': '주유',
        'pt': 'Combustível',
        'zh': '加油/燃油',
      },
      'exp_car_maintenance': {
        'tr': 'Bakım',
        'en': 'Maintenance',
        'de': 'Wartung',
        'es': 'Mantenimiento',
        'fr': 'Entretien',
        'it': 'Manutenzione',
        'ja': '車検・整備',
        'ko': '차량 정비',
        'pt': 'Manutenção',
        'zh': '车辆保养',
      },
      'exp_car_parking': {
        'tr': 'Otopark',
        'en': 'Parking',
        'de': 'Parken',
        'es': 'Aparcamiento',
        'fr': 'Parking',
        'it': 'Parcheggio',
        'ja': '駐車場代',
        'ko': '주차 요금',
        'pt': 'Estacionamento',
        'zh': '停车费',
      },
      'exp_car_wash': {
        'tr': 'Oto Yıkama',
        'en': 'Car Wash',
        'de': 'Autowäsche',
        'es': 'Lavado de autos',
        'fr': 'Lavage auto',
        'it': 'Autolavaggio',
        'ja': '洗車代',
        'ko': '세차',
        'pt': 'Lava-jato',
        'zh': '洗车',
      },
      'exp_car_toll': {
        'tr': 'Geçiş Ücreti',
        'en': 'Tolls',
        'de': 'Maut',
        'es': 'Peajes',
        'fr': 'Péages',
        'it': 'Pedaggi',
        'ja': '高速・通行料',
        'ko': '통행료',
        'pt': 'Pedágios',
        'zh': '路桥费',
      },
      'exp_car_insurance': {
        'tr': 'Araç Sigortası',
        'en': 'Car Insurance',
        'de': 'Kfz-Versicherung',
        'es': 'Seguro de auto',
        'fr': 'Assurance auto',
        'it': 'Assicurazione auto',
        'ja': '自動車保険',
        'ko': '차량 보험',
        'pt': 'Seguro auto',
        'zh': '车辆保险',
      },
      'exp_car_tax': {
        'tr': 'Araç Vergisi',
        'en': 'Car Tax',
        'de': 'Kfz-Steuer',
        'es': 'Impuesto de circulación',
        'fr': 'Taxe auto',
        'it': 'Tassa automobilistica',
        'ja': '自動車税',
        'ko': '자동차세',
        'pt': 'IPVA',
        'zh': '车船税',
      },
      'exp_car_rental': {
        'tr': 'Araç Kiralama',
        'en': 'Car Rental',
        'de': 'Autovermietung',
        'es': 'Alquiler de coches',
        'fr': 'Location de voiture',
        'it': 'Noleggio auto',
        'ja': 'レンタカー',
        'ko': '렌터카',
        'pt': 'Aluguel de carro',
        'zh': '租车',
      },
      
      // Giyim
      'exp_cloth': {
        'tr': 'Giyim',
        'en': 'Clothing',
        'de': 'Kleidung',
        'es': 'Ropa',
        'fr': 'Vêtements',
        'it': 'Abbigliamento',
        'ja': '衣類',
        'ko': '의류',
        'pt': 'Vestuário',
        'zh': '服装',
      },
      'exp_cloth_daily': {
        'tr': 'Günlük Giyim',
        'en': 'Daily Wear',
        'de': 'Alltagskleidung',
        'es': 'Ropa de diario',
        'fr': 'Tenue de tous les jours',
        'it': 'Abbigliamento quotidiano',
        'ja': '普段着',
        'ko': '일상복',
        'pt': 'Roupa casual',
        'zh': '日常便服',
      },
      'exp_cloth_shoes': {
        'tr': 'Ayakkabı',
        'en': 'Shoes',
        'de': 'Schuhe',
        'es': 'Zapatos',
        'fr': 'Chaussures',
        'it': 'Scarpe',
        'ja': '靴',
        'ko': '신발',
        'pt': 'Sapatos',
        'zh': '鞋子',
      },
      'exp_cloth_acc': {
        'tr': 'Aksesuar',
        'en': 'Accessory',
        'de': 'Accessoires',
        'es': 'Accesorio',
        'fr': 'Accessoire',
        'it': 'Accessorio',
        'ja': 'アクセサリー',
        'ko': '액세서리',
        'pt': 'Acessório',
        'zh': '配饰',
      },
      'exp_cloth_tailor': {
        'tr': 'Terzi',
        'en': 'Tailor',
        'de': 'Schneider',
        'es': 'Sastre',
        'fr': 'Tailleur',
        'it': 'Sarto',
        'ja': '仕立て屋',
        'ko': '재단사',
        'pt': 'Alfaiate',
        'zh': '裁缝',
      },
      
      // Kişisel Bakım
      'exp_beauty': {
        'tr': 'Kişisel Bakım',
        'en': 'Personal Care',
        'de': 'Körperpflege',
        'es': 'Cuidado personal',
        'fr': 'Soins personnels',
        'it': 'Cura della persona',
        'ja': '美容・理容',
        'ko': '미용 및 뷰티',
        'pt': 'Cuidado pessoal',
        'zh': '个人护理',
      },
      'exp_beauty_salon': {
        'tr': 'Kuaför',
        'en': 'Hairdresser',
        'de': 'Friseur',
        'es': 'Peluquería',
        'fr': 'Coiffeur',
        'it': 'Parrucchiere',
        'ja': '美容院・理髪店',
        'ko': '미용실',
        'pt': 'Cabeleireiro',
        'zh': '理发美发',
      },
      'exp_beauty_cosmetics': {
        'tr': 'Kozmetik',
        'en': 'Cosmetics',
        'de': 'Kosmetik',
        'es': 'Cosméticos',
        'fr': 'Cosmétiques',
        'it': 'Cosmetici',
        'ja': '化粧品',
        'ko': '화장품',
        'pt': 'Cosméticos',
        'zh': '化妆品',
      },
      'exp_beauty_spa': {
        'tr': 'Spa',
        'en': 'Spa',
        'de': 'Wellness',
        'es': 'Spa',
        'fr': 'Spa',
        'it': 'Spa',
        'ja': 'スパ・温泉',
        'ko': '스파',
        'pt': 'Spa',
        'zh': '水疗SPA',
      },
      'exp_beauty_esthetics': {
        'tr': 'Estetik',
        'en': 'Esthetics',
        'de': 'Ästhetik',
        'es': 'Estética',
        'fr': 'Esthétique',
        'it': 'Estetica',
        'ja': 'エステ',
        'ko': '피부 관리',
        'pt': 'Estética',
        'zh': '美容医美',
      },
      
      // Sağlık
      'exp_health': {
        'tr': 'Sağlık',
        'en': 'Health',
        'de': 'Gesundheit',
        'es': 'Salud',
        'fr': 'Santé',
        'it': 'Salute',
        'ja': '医療・健康',
        'ko': '건강',
        'pt': 'Saúde',
        'zh': '医疗健康',
      },
      'exp_health_doctor': {
        'tr': 'Muayene',
        'en': 'Doctor',
        'de': 'Arzt',
        'es': 'Médico',
        'fr': 'Médecin',
        'it': 'Medico',
        'ja': '医師・診察',
        'ko': '진료',
        'pt': 'Médico',
        'zh': '医生诊疗',
      },
      'exp_health_medicine': {
        'tr': 'İlaç',
        'en': 'Medicine',
        'de': 'Medizin',
        'es': 'Medicina',
        'fr': 'Médicament',
        'it': 'Farmaci',
        'ja': '薬・処方箋',
        'ko': '약값',
        'pt': 'Medicamentos',
        'zh': '药品',
      },
      'exp_health_dentist': {
        'tr': 'Diş',
        'en': 'Dentist',
        'de': 'Zahnarzt',
        'es': 'Dentista',
        'fr': 'Dentiste',
        'it': 'Dentista',
        'ja': '歯医者',
        'ko': '치과',
        'pt': 'Dentista',
        'zh': '牙科',
      },
      'exp_health_surgery': {
        'tr': 'Ameliyat',
        'en': 'Surgery',
        'de': 'Operation',
        'es': 'Cirugía',
        'fr': 'Chirurgie',
        'it': 'Chirurgia',
        'ja': '手術',
        'ko': '수술',
        'pt': 'Cirurgia',
        'zh': '手术',
      },
      'exp_health_optics': {
        'tr': 'Gözlük',
        'en': 'Optics',
        'de': 'Optik',
        'es': 'Óptica',
        'fr': 'Optique',
        'it': 'Ottica',
        'ja': '眼鏡・コンタクト',
        'ko': '안경',
        'pt': 'Óptica',
        'zh': '眼镜配镜',
      },
      'exp_health_veterinary': {
        'tr': 'Veteriner',
        'en': 'Veterinary',
        'de': 'Tierarzt',
        'es': 'Veterinario',
        'fr': 'Vétérinaire',
        'it': 'Veterinario',
        'ja': '獣医・ペット医療',
        'ko': '동물병원',
        'pt': 'Veterinário',
        'zh': '宠物医院',
      },
      'exp_health_therapy': {
        'tr': 'Terapi',
        'en': 'Therapy',
        'de': 'Therapie',
        'es': 'Terapia',
        'fr': 'Thérapie',
        'it': 'Terapia',
        'ja': 'セラピー・カウンセリング',
        'ko': '치료',
        'pt': 'Terapia',
        'zh': '心理咨询/理疗',
      },
      'exp_health_supplements': {
        'tr': 'Destek Gıda',
        'en': 'Supplements',
        'de': 'Nahrungsergänzungsmittel',
        'es': 'Suplementos',
        'fr': 'Compléments',
        'it': 'Integratori',
        'ja': 'サプリメント',
        'ko': '영양제',
        'pt': 'Suplementos',
        'zh': '保健品',
      },
      'exp_health_insurance': {
        'tr': 'Sağlık Sigortası',
        'en': 'Health Insurance',
        'de': 'Krankenversicherung',
        'es': 'Seguro de salud',
        'fr': 'Assurance maladie',
        'it': 'Assicurazione sanitaria',
        'ja': '健康保険',
        'ko': '건강 보험',
        'pt': 'Seguro de saúde',
        'zh': '医疗保险',
      },
      
      // Abonelikler
      'exp_sub': {
        'tr': 'Abonelikler',
        'en': 'Subscriptions',
        'de': 'Abonnements',
        'es': 'Suscripciones',
        'fr': 'Abonnements',
        'it': 'Abbonamenti',
        'ja': 'サブスクリプション',
        'ko': '구독',
        'pt': 'Assinaturas',
        'zh': '订阅服务',
      },
      'exp_sub_stream': {
        'tr': 'Dizi',
        'en': 'Streaming',
        'de': 'Streaming',
        'es': 'Streaming',
        'fr': 'Streaming',
        'it': 'Streaming',
        'ja': '動画配信サービス',
        'ko': '스트리밍',
        'pt': 'Streaming',
        'zh': '流媒体',
      },
      'exp_sub_music': {
        'tr': 'Müzik',
        'en': 'Music',
        'de': 'Musik',
        'es': 'Música',
        'fr': 'Musique',
        'it': 'Musica',
        'ja': '音楽配信サービス',
        'ko': '음악 구독',
        'pt': 'Música',
        'zh': '音乐订阅',
      },
      'exp_sub_gym': {
        'tr': 'Spor Salonu',
        'en': 'Gym',
        'de': 'Fitnessstudio',
        'es': 'Gimnasio',
        'fr': 'Salle de sport',
        'it': 'Palestra',
        'ja': 'ジム',
        'ko': '헬스장',
        'pt': 'Academia',
        'zh': '健身房',
      },
      'exp_sub_software': {
        'tr': 'Yazılım',
        'en': 'Software',
        'de': 'Software',
        'es': 'Software',
        'fr': 'Logiciel',
        'it': 'Software',
        'ja': 'ソフトウェア',
        'ko': '소프트웨어 구독',
        'pt': 'Software',
        'zh': '软件订阅',
      },
      'exp_sub_publishing': {
        'tr': 'Yayın',
        'en': 'Publishing',
        'de': 'Verlagswesen',
        'es': 'Publicaciones',
        'fr': 'Édition',
        'it': 'Editoria',
        'ja': '出版・電子書籍',
        'ko': '출판 구독',
        'pt': 'Publicações',
        'zh': '图书报刊订阅',
      },
      'exp_sub_cloud': {
        'tr': 'Bulut Depolama',
        'en': 'Cloud Storage',
        'de': 'Cloud-Speicher',
        'es': 'Almacenamiento en la nube',
        'fr': 'Stockage cloud',
        'it': 'Cloud storage',
        'ja': 'クラウドストレージ',
        'ko': '클라우드 스토리지',
        'pt': 'Armazenamento em nuvem',
        'zh': '云存储',
      },
      
      // Eğlence
      'exp_fun': {
        'tr': 'Eğlence',
        'en': 'Entertainment',
        'de': 'Unterhaltung',
        'es': 'Entretenimiento',
        'fr': 'Divertissement',
        'it': 'Intrattenimento',
        'ja': '娯楽・レジャー',
        'ko': '여가 및 문화',
        'pt': 'Entretenimento',
        'zh': '娱乐休闲',
      },
      'exp_fun_cinema': {
        'tr': 'Sinema',
        'en': 'Cinema',
        'de': 'Kino',
        'es': 'Cine',
        'fr': 'Cinéma',
        'it': 'Cinema',
        'ja': '映画館',
        'ko': '영화관',
        'pt': 'Cinema',
        'zh': '电影院',
      },
      'exp_fun_concert': {
        'tr': 'Konser',
        'en': 'Concert',
        'de': 'Konzert',
        'es': 'Concierto',
        'fr': 'Concert',
        'it': 'Concerto',
        'ja': 'コンサート',
        'ko': '콘서트',
        'pt': 'Show/Concerto',
        'zh': '演唱会/音乐会',
      },
      'exp_fun_event': {
        'tr': 'Etkinlik',
        'en': 'Event',
        'de': 'Event',
        'es': 'Evento',
        'fr': 'Événement',
        'it': 'Evento',
        'ja': 'イベント',
        'ko': '이벤트',
        'pt': 'Evento',
        'zh': '活动展览',
      },
      'exp_fun_game': {
        'tr': 'Oyun',
        'en': 'Gaming',
        'de': 'Gaming',
        'es': 'Videojuegos',
        'fr': 'Jeux',
        'it': 'Gaming',
        'ja': 'ゲーム',
        'ko': '게임',
        'pt': 'Jogos',
        'zh': '游戏',
      },
      'exp_fun_hobby': {
        'tr': 'Hobi',
        'en': 'Hobby',
        'de': 'Hobby',
        'es': 'Hobby',
        'fr': 'Hobby',
        'it': 'Hobby',
        'ja': '趣味',
        'ko': '취미',
        'pt': 'Hobby',
        'zh': '兴趣爱好',
      },
      'exp_fun_gambling': {
        'tr': 'Şans Oyunları',
        'en': 'Gambling',
        'de': 'Glücksspiel',
        'es': 'Apuestas',
        'fr': 'Jeux de hasard',
        'it': 'Gioco d\'azzardo',
        'ja': 'ギャンブル',
        'ko': '복권',
        'pt': 'Loterias/Apostas',
        'zh': '彩票博彩',
      },
      
      // Eğitim
      'exp_edu': {
        'tr': 'Eğitim',
        'en': 'Education',
        'de': 'Bildung',
        'es': 'Educación',
        'fr': 'Éducation',
        'it': 'Istruzione',
        'ja': '教育',
        'ko': '교육',
        'pt': 'Educação',
        'zh': '教育培训',
      },
      'exp_edu_school': {
        'tr': 'Okul',
        'en': 'School',
        'de': 'Schule',
        'es': 'Escuela',
        'fr': 'École',
        'it': 'Scuola',
        'ja': '学校',
        'ko': '학교',
        'pt': 'Escola',
        'zh': '学校学费',
      },
      'exp_edu_course': {
        'tr': 'Kurs',
        'en': 'Course',
        'de': 'Kurs',
        'es': 'Curso',
        'fr': 'Cours',
        'it': 'Corso',
        'ja': '講習・講座',
        'ko': '강의',
        'pt': 'Curso',
        'zh': '课程培训',
      },
      'exp_edu_book': {
        'tr': 'Kitap',
        'en': 'Book',
        'de': 'Buch',
        'es': 'Libro',
        'fr': 'Livre',
        'it': 'Libro',
        'ja': '書籍・教科書',
        'ko': '도서',
        'pt': 'Livro',
        'zh': '图书教材',
      },
      'exp_edu_stationery': {
        'tr': 'Kırtasiye',
        'en': 'Stationery',
        'de': 'Schreibwaren',
        'es': 'Papelería',
        'fr': 'Papeterie',
        'it': 'Cancelleria',
        'ja': '文房具',
        'ko': '문구',
        'pt': 'Papelaria',
        'zh': '文具用品',
      },
      'exp_edu_exams': {
        'tr': 'Sınavlar',
        'en': 'Exams',
        'de': 'Prüfungen',
        'es': 'Exámenes',
        'fr': 'Examens',
        'it': 'Esami',
        'ja': '試験・受験料',
        'ko': '시험',
        'pt': 'Exames/Provas',
        'zh': '考试报名费',
      },
      
      // Aile
      'exp_family': {
        'tr': 'Aile',
        'en': 'Family',
        'de': 'Familie',
        'es': 'Familia',
        'fr': 'Famille',
        'it': 'Famiglia',
        'ja': '家族',
        'ko': '가족',
        'pt': 'Família',
        'zh': '家庭开支',
      },
      'exp_family_baby': {
        'tr': 'Bebek',
        'en': 'Baby',
        'de': 'Baby',
        'es': 'Bebé',
        'fr': 'Bébé',
        'it': 'Neonato',
        'ja': 'ベビー用品',
        'ko': '육아',
        'pt': 'Bebê',
        'zh': '母婴用品',
      },
      'exp_family_toy': {
        'tr': 'Oyuncak',
        'en': 'Toy',
        'de': 'Spielzeug',
        'es': 'Juguete',
        'fr': 'Jouet',
        'it': 'Giocattolo',
        'ja': 'おもちゃ',
        'ko': '장난감',
        'pt': 'Brinquedos',
        'zh': '玩具',
      },
      'exp_family_allowance': {
        'tr': 'Harçlık',
        'en': 'Allowance',
        'de': 'Tasgeld',
        'es': 'Paga',
        'fr': 'Argent de poche',
        'it': 'Paghetta',
        'ja': '小遣い',
        'ko': '용돈',
        'pt': 'Mesada',
        'zh': '零花钱',
      },
      'exp_family_daycare': {
        'tr': 'Kreş',
        'en': 'Daycare',
        'de': 'Kita',
        'es': 'Guardería',
        'fr': 'Crèche',
        'it': 'Asilo nido',
        'ja': '保育園・託児所',
        'ko': '어린이집',
        'pt': 'Creche',
        'zh': '托儿所',
      },
      'exp_family_support': {
        'tr': 'Aile Desteği',
        'en': 'Family Support',
        'de': 'Familienunterstützung',
        'es': 'Apoyo familiar',
        'fr': 'Soutien familial',
        'it': 'Sostegno familiare',
        'ja': '仕送り・家族援助',
        'ko': '생활비 보조',
        'pt': 'Apoio familiar',
        'zh': '赡养费',
      },
      'exp_family_care': {
        'tr': 'Bakıcı',
        'en': 'Caregiver',
        'de': 'Pflegekraft',
        'es': 'Cuidador',
        'fr': 'Aide à domicile',
        'it': 'Badante',
        'ja': '介護・ベビーシッター',
        'ko': '간병인/보육사',
        'pt': 'Cuidador',
        'zh': '保姆看护',
      },
      'exp_family_alimony': {
        'tr': 'Nafaka',
        'en': 'Alimony',
        'de': 'Unterhalt',
        'es': 'Pensión alimenticia',
        'fr': 'Pension alimentaire',
        'it': 'Alimenti',
        'ja': '養育費',
        'ko': '부양비/위자료',
        'pt': 'Pensão alimentícia',
        'zh': '抚养费',
      },
      
      // Alışveriş
      'exp_shopping': {
        'tr': 'Alışveriş',
        'en': 'Shopping',
        'de': 'Einkaufen',
        'es': 'Compras',
        'fr': 'Shopping',
        'it': 'Shopping',
        'ja': '買い物・ショッピング',
        'ko': '쇼핑',
        'pt': 'Compras',
        'zh': '购物零售',
      },
      'exp_shopping_tech': {
        'tr': 'Teknoloji',
        'en': 'Tech',
        'de': 'Technologie',
        'es': 'Tecnología',
        'fr': 'Tech',
        'it': 'Tecnologia',
        'ja': '家電・ガジェット',
        'ko': '전자기기',
        'pt': 'Tecnologia',
        'zh': '数码科技',
      },
      'exp_shopping_furniture': {
        'tr': 'Mobilya',
        'en': 'Furniture',
        'de': 'Möbel',
        'es': 'Muebles',
        'fr': 'Meubles',
        'it': 'Mobili',
        'ja': '家具',
        'ko': '가구',
        'pt': 'Móveis',
        'zh': '家具',
      },
      'exp_shopping_decor': {
        'tr': 'Ev Tekstili',
        'en': 'Decor',
        'de': 'Deko',
        'es': 'Decoración',
        'fr': 'Déco',
        'it': 'Decorazione',
        'ja': 'インテリア・雑貨',
        'ko': '인테리어 소품',
        'pt': 'Decoração',
        'zh': '家居装饰',
      },
      'exp_shopping_kitchen': {
        'tr': 'Mutfak',
        'en': 'Kitchenware',
        'de': 'Küchenutensilien',
        'es': 'Menaje de cocina',
        'fr': 'Ustensiles de cuisine',
        'it': 'Utensili da cucina',
        'ja': 'キッチン用品',
        'ko': '주방용품',
        'pt': 'Utensílios de cozinha',
        'zh': '厨房餐具',
      },
      'exp_shopping_gift': {
        'tr': 'Hediye',
        'en': 'Gift',
        'de': 'Geschenk',
        'es': 'Regalo',
        'fr': 'Cadeau',
        'it': 'Regalo',
        'ja': 'プレゼント',
        'ko': '선물',
        'pt': 'Presente',
        'zh': '礼品送礼',
      },
      'exp_shopping_general': {
        'tr': 'Genel',
        'en': 'General',
        'de': 'Allgemein',
        'es': 'General',
        'fr': 'Général',
        'it': 'Generale',
        'ja': '日常雑貨',
        'ko': '일반 쇼핑',
        'pt': 'Geral',
        'zh': '一般购物',
      },
      'exp_shopping_sports': {
        'tr': 'Spor Ekipmanı',
        'en': 'Sports Equipment',
        'de': 'Sportausrüstung',
        'es': 'Equipo deportivo',
        'fr': 'Équipement de sport',
        'it': 'Attrezzatura sportiva',
        'ja': 'スポーツ用品',
        'ko': '스포츠 용품',
        'pt': 'Equipamento esportivo',
        'zh': '体育装备',
      },
      'exp_shopping_shipping': {
        'tr': 'Kargo',
        'en': 'Shipping',
        'de': 'Versand',
        'es': 'Envío',
        'fr': 'Livraison',
        'it': 'Spedizione',
        'ja': '送料',
        'ko': '배송비',
        'pt': 'Frete',
        'zh': '快递邮费',
      },
      
      // Seyahat
      'exp_travel': {
        'tr': 'Seyahat',
        'en': 'Travel',
        'de': 'Reisen',
        'es': 'Viajes',
        'fr': 'Voyage',
        'it': 'Viaggi',
        'ja': '旅行',
        'ko': '여행',
        'pt': 'Viagem',
        'zh': '旅游度假',
      },
      'exp_travel_hotel': {
        'tr': 'Konaklama',
        'en': 'Hotel',
        'de': 'Hotel',
        'es': 'Hotel',
        'fr': 'Hôtel',
        'it': 'Hotel',
        'ja': '宿泊・ホテル',
        'ko': '숙박',
        'pt': 'Hotel',
        'zh': '酒店住宿',
      },
      'exp_travel_flight': {
        'tr': 'Ulaşım Bileti',
        'en': 'Tickets',
        'de': 'Tickets',
        'es': 'Billetes',
        'fr': 'Billets',
        'it': 'Biglietti',
        'ja': '切符・航空券',
        'ko': '교통 티켓',
        'pt': 'Passagens',
        'zh': '机票车票',
      },
      'exp_travel_tour': {
        'tr': 'Turistik Gezi',
        'en': 'Tour',
        'de': 'Tour',
        'es': 'Tour',
        'fr': 'Visite',
        'it': 'Tour',
        'ja': 'ツアー・観光',
        'ko': '관광',
        'pt': 'Tour/Passeio',
        'zh': '导游跟团',
      },
      'exp_travel_visa': {
        'tr': 'Vize',
        'en': 'Visa',
        'de': 'Visum',
        'es': 'Visa',
        'fr': 'Visa',
        'it': 'Visto',
        'ja': 'ビザ代',
        'ko': '비자',
        'pt': 'Visto',
        'zh': '签证办理',
      },
      
      // Borç
      'exp_debt': {
        'tr': 'Borç',
        'en': 'Debt',
        'de': 'Schulden',
        'es': 'Deuda',
        'fr': 'Dette',
        'it': 'Debito',
        'ja': '借金・債務',
        'ko': '부채 및 채무',
        'pt': 'Dívida',
        'zh': '债务借贷',
      },
      'exp_debt_credit_card': {
        'tr': 'Kredi Kartı',
        'en': 'Credit Card',
        'de': 'Kreditkarte',
        'es': 'Tarjeta de crédito',
        'fr': 'Carte de crédit',
        'it': 'Carta di credito',
        'ja': 'クレジットカード代',
        'ko': '신용카드 대금',
        'pt': 'Cartão de crédito',
        'zh': '信用卡账单',
      },
      'exp_debt_loan': {
        'tr': 'Kredi',
        'en': 'Loan',
        'de': 'Darlehen',
        'es': 'Préstamo',
        'fr': 'Prêt',
        'it': 'Prestito',
        'ja': 'ローン返済',
        'ko': '대출 상환',
        'pt': 'Empréstimo',
        'zh': '贷款还款',
      },
      'exp_debt_personal': {
        'tr': 'Borç Ödeme',
        'en': 'Personal Debt',
        'de': 'Persönliche Schulden',
        'es': 'Deuda personal',
        'fr': 'Dette personnelle',
        'it': 'Debito personale',
        'ja': '個人間借入返済',
        'ko': '개인 채무 상환',
        'pt': 'Dívida pessoal',
        'zh': '偿还个人欠款',
      },
      'exp_debt_lending': {
        'tr': 'Borç Verme',
        'en': 'Lending',
        'de': 'Ausleihen',
        'es': 'Prestar',
        'fr': 'Prêt',
        'it': 'Prestito',
        'ja': '貸付金',
        'ko': '빌려준 돈',
        'pt': 'Empréstimo (cedido)',
        'zh': '借钱出去',
      },
      
      // Birikim ve Yatırım
      'exp_invest': {
        'tr': 'Yatırım',
        'en': 'Investment',
        'de': 'Investition',
        'es': 'Inversión',
        'fr': 'Investissement',
        'it': 'Investimento',
        'ja': '投資',
        'ko': '투자',
        'pt': 'Investimento',
        'zh': '投资理财',
      },
      'exp_invest_stocks': {
        'tr': 'Hisse Senedi',
        'en': 'Stocks',
        'de': 'Aktien',
        'es': 'Acciones',
        'fr': 'Actions',
        'it': 'Azioni',
        'ja': '株式',
        'ko': '주식',
        'pt': 'Ações',
        'zh': '股票',
      },
      'exp_invest_gold': {
        'tr': 'Altın',
        'en': 'Gold',
        'de': 'Gold',
        'es': 'Oro',
        'fr': 'Or',
        'it': 'Oro',
        'ja': '金',
        'ko': '금',
        'pt': 'Ouro',
        'zh': '黄金',
      },
      'exp_invest_crypto': {
        'tr': 'Kripto',
        'en': 'Crypto',
        'de': 'Krypto',
        'es': 'Cripto',
        'fr': 'Crypto',
        'it': 'Cripto',
        'ja': '暗号資産',
        'ko': '암호화폐',
        'pt': 'Cripto',
        'zh': '加密货币',
      },
      'exp_invest_pension': {
        'tr': 'Bireysel Emeklilik',
        'en': 'Pension Savings',
        'de': 'Rentenversicherung',
        'es': 'Jubilación',
        'fr': 'Épargne retraite',
        'it': 'Previdenza complementare',
        'ja': '年金積立',
        'ko': '연금 저축',
        'pt': 'Previdência privada',
        'zh': '养老金储蓄',
      },
      
      // Vergiler
      'exp_tax': {
        'tr': 'Vergiler',
        'en': 'Taxes',
        'de': 'Steuern',
        'es': 'Impuestos',
        'fr': 'Taxes',
        'it': 'Tasse',
        'ja': '税金',
        'ko': '세금',
        'pt': 'Impostos',
        'zh': '税费',
      },
      'exp_tax_income': {
        'tr': 'Gelir Vergisi',
        'en': 'Income Tax',
        'de': 'Einkommensteuer',
        'es': 'Impuesto sobre la renta',
        'fr': 'Impôt sur le revenu',
        'it': 'Imposta sul reddito',
        'ja': '所得税',
        'ko': '소득세',
        'pt': 'Imposto de renda',
        'zh': '个人所得税',
      },
      'exp_tax_fine': {
        'tr': 'Cezalar',
        'en': 'Fines',
        'de': 'Bußgelder',
        'es': 'Multas',
        'fr': 'Amendes',
        'it': 'Multe',
        'ja': '罰金・反則金',
        'ko': '벌금 및 과태료',
        'pt': 'Multas',
        'zh': '罚款罚金',
      },
      'exp_tax_fee': {
        'tr': 'Harçlar',
        'en': 'Fees',
        'de': 'Gebühren',
        'es': 'Tasas',
        'fr': 'Frais',
        'it': 'Tasse/Diritti',
        'ja': '手数料・公租公課',
        'ko': '수수료',
        'pt': 'Taxas',
        'zh': '行政规费',
      },
      
      // Diğer Giderler
      'exp_other': {
        'tr': 'Diğer Giderler',
        'en': 'Other Expenses',
        'de': 'Sonstige Ausgaben',
        'es': 'Otros gastos',
        'fr': 'Autres dépenses',
        'it': 'Altre spese',
        'ja': 'その他雑費',
        'ko': '기타 지출',
        'pt': 'Outras despesas',
        'zh': '其他支出',
      },
      'exp_other_general': {
        'tr': 'Genel Gider',
        'en': 'General',
        'de': 'Allgemein',
        'es': 'General',
        'fr': 'Général',
        'it': 'Generale',
        'ja': '一般雑費',
        'ko': '일반 지출',
        'pt': 'Geral',
        'zh': '一般杂项',
      },
      'exp_other_donation': {
        'tr': 'Bağış',
        'en': 'Donation',
        'de': 'Spende',
        'es': 'Donación',
        'fr': 'Don',
        'it': 'Donazione',
        'ja': '寄付',
        'ko': '기부금',
        'pt': 'Doação',
        'zh': '慈善捐款',
      },
      'exp_other_tip': {
        'tr': 'Bahşiş',
        'en': 'Tip',
        'de': 'Trinkgeld',
        'es': 'Propina',
        'fr': 'Pourboire',
        'it': 'Mancia',
        'ja': 'チップ',
        'ko': '팁',
        'pt': 'Gorjeta',
        'zh': '支付小费',
      },
      'exp_other_bank_fee': {
        'tr': 'Banka Ücreti',
        'en': 'Bank Fee',
        'de': 'Bankgebühr',
        'es': 'Comisión bancaria',
        'fr': 'Frais bancaires',
        'it': 'Commissioni bancarie',
        'ja': '銀行手数料',
        'ko': '은행 수수료',
        'pt': 'Tarifa bancária',
        'zh': '银行服务费',
      },
 
      // ==========================================
      // GELİRLER (INCOMES)
      // ==========================================
      // Maaş
      'inc_salary': {
        'tr': 'Maaş',
        'en': 'Salary',
        'de': 'Gehalt',
        'es': 'Salario',
        'fr': 'Salaire',
        'it': 'Stipendio',
        'ja': '給与',
        'ko': '급여',
        'pt': 'Salário',
        'zh': '薪资',
      },
      'inc_salary_main': {
        'tr': 'Ana Maaş',
        'en': 'Main Salary',
        'de': 'Grundgehalt',
        'es': 'Salario base',
        'fr': 'Salaire de base',
        'it': 'Stipendio base',
        'ja': '基本給',
        'ko': '기본급',
        'pt': 'Salário base',
        'zh': '基本工资',
      },
      'inc_salary_bonus': {
        'tr': 'Prim',
        'en': 'Bonus',
        'de': 'Bonus',
        'es': 'Bonificación',
        'fr': 'Bonus',
        'it': 'Bonus/Premio',
        'ja': 'ボーナス',
        'ko': '보너스/상여금',
        'pt': 'Bônus',
        'zh': '奖金提成',
      },
      'inc_salary_dividend': {
        'tr': 'Kâr Payı',
        'en': 'Dividend',
        'de': 'Dividende',
        'es': 'Dividendo',
        'fr': 'Dividende',
        'it': 'Dividendo',
        'ja': '配当金',
        'ko': '배당금',
        'pt': 'Dividendo',
        'zh': '股息红利',
      },
      'inc_salary_pension': {
        'tr': 'Emeklilik',
        'en': 'Pension',
        'de': 'Rente',
        'es': 'Pensión',
        'fr': 'Pension',
        'it': 'Pensione',
        'ja': '年金',
        'ko': '연금',
        'pt': 'Aposentadoria',
        'zh': '退休金',
      },
      'inc_salary_severance': {
        'tr': 'Tazminat',
        'en': 'Severance',
        'de': 'Abfindung',
        'es': 'Indemnización',
        'fr': 'Indemnité de licenciement',
        'it': 'TFR/Buonuscita',
        'ja': '退職金',
        'ko': '퇴직금',
        'pt': 'Indenização/Rescisão',
        'zh': '遣散费/补偿金',
      },
      
      // Ek Gelir
      'inc_extra': {
        'tr': 'Ek Gelir',
        'en': 'Side Income',
        'de': 'Nebeneinkommen',
        'es': 'Ingresos extras',
        'fr': 'Revenu d\'appoint',
        'it': 'Entrate extra',
        'ja': '副収入',
        'ko': '부수입',
        'pt': 'Renda extra',
        'zh': '兼职副业',
      },
      'inc_extra_freelance': {
        'tr': 'Freelance',
        'en': 'Freelance',
        'de': 'Freelance',
        'es': 'Freelance',
        'fr': 'Freelance',
        'it': 'Freelance',
        'ja': 'フリーランス',
        'ko': '프리랜서 수입',
        'pt': 'Freelance',
        'zh': '自由职业',
      },
      'inc_extra_parttime': {
        'tr': 'Yarı Zamanlı',
        'en': 'Part Time',
        'de': 'Teilzeit',
        'es': 'Tiempo parcial',
        'fr': 'Temps partiel',
        'it': 'Part-time',
        'ja': 'アルバイト',
        'ko': '아르바이트 수입',
        'pt': 'Trabalho temporário',
        'zh': '兼职',
      },
      'inc_extra_commission': {
        'tr': 'Komisyon',
        'en': 'Commission',
        'de': 'Provision',
        'es': 'Comisión',
        'fr': 'Commission',
        'it': 'Provvigione',
        'ja': '手数料収入',
        'ko': '수수료 수입',
        'pt': 'Comissão',
        'zh': '佣金提成',
      },
      'inc_extra_content': {
        'tr': 'İçerik Üreticiliği',
        'en': 'Content Creation',
        'de': 'Content Creation',
        'es': 'Creación de contenido',
        'fr': 'Création de contenu',
        'it': 'Creazione di contenuti',
        'ja': 'コンテンツ制作',
        'ko': '콘텐츠 제작 수입',
        'pt': 'Criação de conteúdo',
        'zh': '内容创作',
      },
      'inc_extra_affiliate': {
        'tr': 'Satış Ortaklığı',
        'en': 'Affiliate',
        'de': 'Affiliate',
        'es': 'Afiliados',
        'fr': 'Affiliation',
        'it': 'Affiliazione',
        'ja': 'アフィリエイト',
        'ko': '제휴 마케팅 수입',
        'pt': 'Marketing de afiliados',
        'zh': '分销推广',
      },
      
      // Yatırım Geliri
      'inc_invest': {
        'tr': 'Yatırım Geliri',
        'en': 'Investment Income',
        'de': 'Kapitalertrag',
        'es': 'Ingresos por inversiones',
        'fr': 'Revenus de placement',
        'it': 'Rendita finanziaria',
        'ja': '投資収益',
        'ko': '투자 수익',
        'pt': 'Rendimento de investimentos',
        'zh': '投资收益',
      },
      'inc_invest_stock': {
        'tr': 'Hisse Senedi',
        'en': 'Stock',
        'de': 'Aktie',
        'es': 'Acciones',
        'fr': 'Actions',
        'it': 'Titoli/Azioni',
        'ja': '株式収益',
        'ko': '주식 수익',
        'pt': 'Ações',
        'zh': '股票收益',
      },
      'inc_invest_crypto': {
        'tr': 'Kripto',
        'en': 'Crypto',
        'de': 'Krypto',
        'es': 'Cripto',
        'fr': 'Crypto',
        'it': 'Cripto',
        'ja': '暗号資産収益',
        'ko': '암호화폐 수익',
        'pt': 'Cripto',
        'zh': '加密货币收益',
      },
      'inc_invest_interest': {
        'tr': 'Faiz',
        'en': 'Interest',
        'de': 'Zinsen',
        'es': 'Intereses',
        'fr': 'Intérêts',
        'it': 'Interessi',
        'ja': '利息・利子',
        'ko': '이자 수익',
        'pt': 'Juros',
        'zh': '利息收益',
      },
      'inc_invest_gold': {
        'tr': 'Altın',
        'en': 'Gold',
        'de': 'Gold',
        'es': 'Oro',
        'fr': 'Or',
        'it': 'Oro',
        'ja': '金収益',
        'ko': '금 수익',
        'pt': 'Ouro',
        'zh': '黄金收益',
      },
      'inc_invest_forex': {
        'tr': 'Döviz Kârı',
        'en': 'Forex',
        'de': 'Devisengewinn',
        'es': 'Divisas',
        'fr': 'Gain de change',
        'it': 'Forex/Cambi',
        'ja': '為替差益',
        'ko': '외환 차익',
        'pt': 'Lucro cambial',
        'zh': '外汇差额',
      },
      'inc_invest_bond': {
        'tr': 'Tahvil',
        'en': 'Bond',
        'de': 'Anleihe',
        'es': 'Bonos',
        'fr': 'Obligation',
        'it': 'Obbligazioni',
        'ja': '債券収益',
        'ko': '채권 수익',
        'pt': 'Títulos/Títulos públicos',
        'zh': '债券收益',
      },
      
      // Kira Geliri
      'inc_rent': {
        'tr': 'Kira Geliri',
        'en': 'Rental Income',
        'de': 'Mieteinnahmen',
        'es': 'Ingresos por alquiler',
        'fr': 'Revenus locatifs',
        'it': 'Reddito da locazione',
        'ja': '家賃収入',
        'ko': '임대 소득',
        'pt': 'Recebimento de aluguel',
        'zh': '租金收入',
      },
      'inc_rent_home': {
        'tr': 'Konut Kirası',
        'en': 'Home Rent',
        'de': 'Hausvermietung',
        'es': 'Alquiler de vivienda',
        'fr': 'Location de maison',
        'it': 'Affitto casa',
        'ja': '住宅賃貸収入',
        'ko': '주택 임대료',
        'pt': 'Aluguel residencial',
        'zh': '住宅租金',
      },
      'inc_rent_office': {
        'tr': 'İş Yeri Kirası',
        'en': 'Office Rent',
        'de': 'Bürovermietung',
        'es': 'Alquiler de oficina',
        'fr': 'Location de bureau',
        'it': 'Affitto ufficio',
        'ja': 'オフィス賃貸収入',
        'ko': '사무실 임대료',
        'pt': 'Aluguel comercial',
        'zh': '商铺租金',
      },
      'inc_rent_car': {
        'tr': 'Araç Kirası',
        'en': 'Car Rent',
        'de': 'Autovermietung',
        'es': 'Alquiler de autos',
        'fr': 'Location de voiture',
        'it': 'Noleggio auto',
        'ja': 'レンタカー事業収入',
        'ko': '차량 임대료',
        'pt': 'Locação de veículo',
        'zh': '租车租金',
      },
      'inc_rent_equipment': {
        'tr': 'Ekipman Kirası',
        'en': 'Equipment Rent',
        'de': 'Gerätevermietung',
        'es': 'Alquiler de equipos',
        'fr': 'Location d\'équipement',
        'it': 'Noleggio attrezzature',
        'ja': '機器賃貸収入',
        'ko': '장비 임대료',
        'pt': 'Aluguel de equipamentos',
        'zh': '设备租金',
      },
      
      // Burs
      'inc_scholarship': {
        'tr': 'Burs',
        'en': 'Scholarship',
        'de': 'Stipendium',
        'es': 'Beca',
        'fr': 'Bourse',
        'it': 'Borsa di studio',
        'ja': '奨学金',
        'ko': '장학금',
        'pt': 'Bolsa de estudos',
        'zh': '奖学金',
      },
      'inc_scholarship_award': {
        'tr': 'Öğrenim Bursu',
        'en': 'Scholarship',
        'de': 'Studienstipendium',
        'es': 'Beca escolar',
        'fr': 'Bourse d\'études',
        'it': 'Borsa di studio',
        'ja': '学業奨学金',
        'ko': '학업 장학금',
        'pt': 'Bolsa de estudos',
        'zh': '助学金',
      },
      'inc_scholarship_loan': {
        'tr': 'Öğrenim Kredisi',
        'en': 'Student Loan',
        'de': 'Studienkredit',
        'es': 'Préstamo estudiantil',
        'fr': 'Prêt étudiant',
        'it': 'Prestito studentesco',
        'ja': '学生ローン',
        'ko': '학자금 대출',
        'pt': 'FIES/Crédito universitário',
        'zh': '学子贷款',
      },
      'inc_scholarship_gov': {
        'tr': 'Sosyal Yardım',
        'en': 'Support',
        'de': 'Sozialhilfe',
        'es': 'Apoyo estatal',
        'fr': 'Aide sociale',
        'it': 'Assistenza sociale',
        'ja': '公的援助・給付金',
        'ko': '정부 보조금',
        'pt': 'Benefício social',
        'zh': '社会救助/补助',
      },
      'inc_scholarship_grant': {
        'tr': 'Proje Desteği',
        'en': 'Project Grant',
        'de': 'Projektförderung',
        'es': 'Subvención de proyecto',
        'fr': 'Subvention de projet',
        'it': 'Finanziamento progetto',
        'ja': '研究・助成金',
        'ko': '프로젝트 지원금',
        'pt': 'Subvenção de projeto',
        'zh': '项目资助',
      },
      
      // Satış
      'inc_sale': {
        'tr': 'Satış',
        'en': 'Sales',
        'de': 'Verkäufe',
        'es': 'Ventas',
        'fr': 'Ventes',
        'it': 'Vendite',
        'ja': '売上・販売収入',
        'ko': '판매 수익',
        'pt': 'Vendas',
        'zh': '销售收入',
      },
      'inc_sale_online': {
        'tr': 'Online Satış',
        'en': 'Online Sale',
        'de': 'Online-Verkauf',
        'es': 'Venta online',
        'fr': 'Vente en ligne',
        'it': 'Vendita online',
        'ja': 'ネット販売',
        'ko': '온라인 판매',
        'pt': 'Venda online',
        'zh': '网络销售',
      },
      'inc_sale_physical': {
        'tr': 'İkinci El Satış',
        'en': 'Second Hand',
        'de': 'Gebrauchtwaren',
        'es': 'Segunda mano',
        'fr': 'Occasion',
        'it': 'Seconda mano',
        'ja': '物品・中古販売',
        'ko': '중고 판매',
        'pt': 'Venda de usados',
        'zh': '二手交易',
      },
      'inc_sale_vehicle': {
        'tr': 'Araç Satışı',
        'en': 'Vehicle Sale',
        'de': 'Fahrzeugverkauf',
        'es': 'Venta de vehículo',
        'fr': 'Vente de véhicule',
        'it': 'Vendita veicolo',
        'ja': '車両売却',
        'ko': '차량 매각',
        'pt': 'Venda de veículo',
        'zh': '汽车出售',
      },
      'inc_sale_property': {
        'tr': 'Gayrimenkul Satışı',
        'en': 'Real Estate Sale',
        'de': 'Immobilienverkauf',
        'es': 'Venta de propiedad',
        'fr': 'Vente immobilière',
        'it': 'Vendita immobile',
        'ja': '不動産売却',
        'ko': '부동산 매각',
        'pt': 'Venda de imóvel',
        'zh': '房屋出售',
      },
      
      // Hediye
      'inc_gift': {
        'tr': 'Hediye',
        'en': 'Gift',
        'de': 'Geschenk',
        'es': 'Regalo',
        'fr': 'Cadeau',
        'it': 'Regalo',
        'ja': 'プレゼント・ギフト',
        'ko': '선물',
        'pt': 'Presente',
        'zh': '礼品礼物',
      },
      'inc_gift_general': {
        'tr': 'Nakit Hediye',
        'en': 'Gift',
        'de': 'Geldgeschenk',
        'es': 'Regalo en efectivo',
        'fr': 'Cadeau en argent',
        'it': 'Regalo in denaro',
        'ja': '現金祝・お祝い金',
        'ko': '현금 선물',
        'pt': 'Presente em dinheiro',
        'zh': '礼金红包',
      },
      'inc_gift_award': {
        'tr': 'Ödül',
        'en': 'Award',
        'de': 'Auszeichnung',
        'es': 'Premio',
        'fr': 'Prix/Récompense',
        'it': 'Premio',
        'ja': '賞金',
        'ko': '포상금/상금',
        'pt': 'Prêmio',
        'zh': '奖金奖品',
      },
      'inc_gift_inheritance': {
        'tr': 'Miras',
        'en': 'Inheritance',
        'de': 'Erbe',
        'es': 'Herencia',
        'fr': 'Héritage',
        'it': 'Eredità',
        'ja': '相続',
        'ko': '상속',
        'pt': 'Herança',
        'zh': '遗产继承',
      },
      'inc_gift_alimony': {
        'tr': 'Nafaka',
        'en': 'Alimony',
        'de': 'Unterhalt',
        'es': 'Pensión alimenticia',
        'fr': 'Pension alimentaire',
        'it': 'Alimenti',
        'ja': '養育費・慰謝料',
        'ko': '위자료',
        'pt': 'Pensão alimentícia',
        'zh': '赡养费/抚养费',
      },
      'inc_gift_allowance': {
        'tr': 'Harçlık',
        'en': 'Allowance',
        'de': 'Tasgeld',
        'es': 'Paga',
        'fr': 'Argent de poche',
        'it': 'Paghetta',
        'ja': '小遣い',
        'ko': '용돈',
        'pt': 'Mesada',
        'zh': '零花钱',
      },
      
      // Diğer Gelirler
      'inc_other': {
        'tr': 'Diğer Gelirler',
        'en': 'Other Incomes',
        'de': 'Sonstige Einnahmen',
        'es': 'Otros ingresos',
        'fr': 'Autres revenus',
        'it': 'Altre entrate',
        'ja': 'その他収入',
        'ko': '기타 수입',
        'pt': 'Outras receitas',
        'zh': '其他收入',
      },
      'inc_other_general': {
        'tr': 'Genel Gelir',
        'en': 'Other',
        'de': 'Sonstiges',
        'es': 'Otros',
        'fr': 'Autre',
        'it': 'Altro',
        'ja': 'その他雑収入',
        'ko': '일반 수입',
        'pt': 'Geral',
        'zh': '一般杂项收入',
      },
      'inc_other_refund': {
        'tr': 'İade',
        'en': 'Refund',
        'de': 'Rückerstattung',
        'es': 'Reembolso',
        'fr': 'Remboursement',
        'it': 'Rimborso',
        'ja': '返金・キャッシュバック',
        'ko': '환불',
        'pt': 'Reembolso',
        'zh': '退款',
      },
      'inc_other_lottery': {
        'tr': 'Şans Oyunları',
        'en': 'Lottery',
        'de': 'Lotterie',
        'es': 'Lotería',
        'fr': 'Loterie',
        'it': 'Lotteria',
        'ja': '宝くじ',
        'ko': '복권 당첨금',
        'pt': 'Loteria',
        'zh': '彩票中奖',
      },
      'inc_other_collection': {
        'tr': 'Borç Tahsilatı',
        'en': 'Debt Collection',
        'de': 'Inkasso',
        'es': 'Cobro de deudas',
        'fr': 'Recouvrement de créance',
        'it': 'Recupero crediti',
        'ja': '債権回収',
        'ko': '대금 회수',
        'pt': 'Cobrança de dívida',
        'zh': '欠款收回',
      },
      'inc_other_cashback': {
        'tr': 'Cashback',
        'en': 'Cashback',
        'de': 'Cashback',
        'es': 'Cashback',
        'fr': 'Cashback',
        'it': 'Cashback',
        'ja': 'キャッシュバック',
        'ko': '캐시백',
        'pt': 'Cashback',
        'zh': '消费返现',
      },
      'inc_other_tax_refund': {
        'tr': 'Vergi İadesi',
        'en': 'Tax Refund',
        'de': 'Steuererstattung',
        'es': 'Devolución de impuestos',
        'fr': 'Remboursement d\'impôt',
        'it': 'Rimborso fiscale',
        'ja': '還付金',
        'ko': '세금 환급',
        'pt': 'Restituição de imposto',
        'zh': '税退',
      },
    };
    
    final localized = names[id];
    if (localized != null) {
      return localized[locale] ?? localized['en'] ?? '';
    }
    return '';
  }

  static List<Map<String, dynamic>> getExpenseCategories(BuildContext context, AppLocalizations l10n) => [
    {
      'id': 'exp_rent',
      'name': getCategoryName(context, 'exp_rent'),
      'icon': IconUtils.getIcon('exp_rent'),
      'color': IconUtils.getColor('exp_rent'),
      'subModels': [
        {
          'id': 'exp_rent_home',
          'name': getCategoryName(context, 'exp_rent_home'),
          'icon': IconUtils.getIcon('exp_rent_home'),
        },
        {
          'id': 'exp_rent_office',
          'name': getCategoryName(context, 'exp_rent_office'),
          'icon': IconUtils.getIcon('exp_rent_office'),
        },
        {
          'id': 'exp_rent_mortgage',
          'name': getCategoryName(context, 'exp_rent_mortgage'),
          'icon': IconUtils.getIcon('exp_rent_mortgage'),
        },
        {
          'id': 'exp_rent_maintenance',
          'name': getCategoryName(context, 'exp_rent_maintenance'),
          'icon': IconUtils.getIcon('exp_rent_maintenance'),
        },
        {
          'id': 'exp_rent_storage',
          'name': getCategoryName(context, 'exp_rent_storage'),
          'icon': IconUtils.getIcon('exp_rent_storage'),
        },
        {
          'id': 'exp_rent_insurance',
          'name': getCategoryName(context, 'exp_rent_insurance'),
          'icon': IconUtils.getIcon('exp_rent_insurance'),
        },
        {
          'id': 'exp_rent_moving',
          'name': getCategoryName(context, 'exp_rent_moving'),
          'icon': IconUtils.getIcon('exp_rent_moving'),
        },
        {
          'id': 'exp_rent_dorm',
          'name': getCategoryName(context, 'exp_rent_dorm'),
          'icon': IconUtils.getIcon('exp_rent_dorm'),
        },
        {
          'id': 'exp_rent_room',
          'name': getCategoryName(context, 'exp_rent_room'),
          'icon': IconUtils.getIcon('exp_rent_room'),
        },
      ],
    },
    {
      'id': 'exp_bill',
      'name': getCategoryName(context, 'exp_bill'),
      'icon': IconUtils.getIcon('exp_bill'),
      'color': IconUtils.getColor('exp_bill'),
      'subModels': [
        {
          'id': 'exp_bill_electricity',
          'name': getCategoryName(context, 'exp_bill_electricity'),
          'icon': IconUtils.getIcon('exp_bill_electricity'),
        },
        {
          'id': 'exp_bill_water',
          'name': getCategoryName(context, 'exp_bill_water'),
          'icon': IconUtils.getIcon('exp_bill_water'),
        },
        {
          'id': 'exp_bill_gas',
          'name': getCategoryName(context, 'exp_bill_gas'),
          'icon': IconUtils.getIcon('exp_bill_gas'),
        },
        {
          'id': 'exp_bill_internet',
          'name': getCategoryName(context, 'exp_bill_internet'),
          'icon': IconUtils.getIcon('exp_bill_internet'),
        },
        {
          'id': 'exp_bill_phone',
          'name': getCategoryName(context, 'exp_bill_phone'),
          'icon': IconUtils.getIcon('exp_bill_phone'),
        },
        {
          'id': 'exp_bill_dues',
          'name': getCategoryName(context, 'exp_bill_dues'),
          'icon': IconUtils.getIcon('exp_bill_dues'),
        },
        {
          'id': 'exp_bill_tv',
          'name': getCategoryName(context, 'exp_bill_tv'),
          'icon': IconUtils.getIcon('exp_bill_tv'),
        },
      ],
    },
    {
      'id': 'exp_grocery',
      'name': getCategoryName(context, 'exp_grocery'),
      'icon': IconUtils.getIcon('exp_grocery'),
      'color': IconUtils.getColor('exp_grocery'),
      'subModels': [
        {
          'id': 'exp_grocery_food',
          'name': getCategoryName(context, 'exp_grocery_food'),
          'icon': IconUtils.getIcon('exp_grocery_food'),
        },
        {
          'id': 'exp_grocery_cleaning',
          'name': getCategoryName(context, 'exp_grocery_cleaning'),
          'icon': IconUtils.getIcon('exp_grocery_cleaning'),
        },
        {
          'id': 'exp_grocery_drink',
          'name': getCategoryName(context, 'exp_grocery_drink'),
          'icon': IconUtils.getIcon('exp_grocery_drink'),
        },
        {
          'id': 'exp_grocery_pet',
          'name': getCategoryName(context, 'exp_grocery_pet'),
          'icon': IconUtils.getIcon('exp_grocery_pet'),
        },
        {
          'id': 'exp_grocery_hygiene',
          'name': getCategoryName(context, 'exp_grocery_hygiene'),
          'icon': IconUtils.getIcon('exp_grocery_hygiene'),
        },
        {
          'id': 'exp_grocery_tobacco',
          'name': getCategoryName(context, 'exp_grocery_tobacco'),
          'icon': IconUtils.getIcon('exp_grocery_tobacco'),
        },
        {
          'id': 'exp_grocery_alcohol',
          'name': getCategoryName(context, 'exp_grocery_alcohol'),
          'icon': IconUtils.getIcon('exp_grocery_alcohol'),
        },
      ],
    },
    {
      'id': 'exp_dining',
      'name': getCategoryName(context, 'exp_dining'),
      'icon': IconUtils.getIcon('exp_dining'),
      'color': IconUtils.getColor('exp_dining'),
      'subModels': [
        {
          'id': 'exp_dining_restaurant',
          'name': getCategoryName(context, 'exp_dining_restaurant'),
          'icon': IconUtils.getIcon('exp_dining_restaurant'),
        },
        {
          'id': 'exp_dining_cafe',
          'name': getCategoryName(context, 'exp_dining_cafe'),
          'icon': IconUtils.getIcon('exp_dining_cafe'),
        },
        {
          'id': 'exp_dining_fastfood',
          'name': getCategoryName(context, 'exp_dining_fastfood'),
          'icon': IconUtils.getIcon('exp_dining_fastfood'),
        },
        {
          'id': 'exp_dining_delivery',
          'name': getCategoryName(context, 'exp_dining_delivery'),
          'icon': IconUtils.getIcon('exp_dining_delivery'),
        },
        {
          'id': 'exp_dining_canteen',
          'name': getCategoryName(context, 'exp_dining_canteen'),
          'icon': IconUtils.getIcon('exp_dining_canteen'),
        },
      ],
    },
    {
      'id': 'exp_trans',
      'name': getCategoryName(context, 'exp_trans'),
      'icon': IconUtils.getIcon('exp_trans'),
      'color': IconUtils.getColor('exp_trans'),
      'subModels': [
        {
          'id': 'exp_trans_bus',
          'name': getCategoryName(context, 'exp_trans_bus'),
          'icon': IconUtils.getIcon('exp_trans_bus'),
        },
        {
          'id': 'exp_trans_taxi',
          'name': getCategoryName(context, 'exp_trans_taxi'),
          'icon': IconUtils.getIcon('exp_trans_taxi'),
        },
        {
          'id': 'exp_trans_intercity',
          'name': getCategoryName(context, 'exp_trans_intercity'),
          'icon': IconUtils.getIcon('exp_trans_intercity'),
        },
        {
          'id': 'exp_trans_scooter',
          'name': getCategoryName(context, 'exp_trans_scooter'),
          'icon': IconUtils.getIcon('exp_trans_scooter'),
        },
      ],
    },
    {
      'id': 'exp_car',
      'name': getCategoryName(context, 'exp_car'),
      'icon': IconUtils.getIcon('exp_car'),
      'color': IconUtils.getColor('exp_car'),
      'subModels': [
        {
          'id': 'exp_car_fuel',
          'name': getCategoryName(context, 'exp_car_fuel'),
          'icon': IconUtils.getIcon('exp_car_fuel'),
        },
        {
          'id': 'exp_car_maintenance',
          'name': getCategoryName(context, 'exp_car_maintenance'),
          'icon': IconUtils.getIcon('exp_car_maintenance'),
        },
        {
          'id': 'exp_car_parking',
          'name': getCategoryName(context, 'exp_car_parking'),
          'icon': IconUtils.getIcon('exp_car_parking'),
        },
        {
          'id': 'exp_car_wash',
          'name': getCategoryName(context, 'exp_car_wash'),
          'icon': IconUtils.getIcon('exp_car_wash'),
        },
        {
          'id': 'exp_car_toll',
          'name': getCategoryName(context, 'exp_car_toll'),
          'icon': IconUtils.getIcon('exp_car_toll'),
        },
        {
          'id': 'exp_car_insurance',
          'name': getCategoryName(context, 'exp_car_insurance'),
          'icon': IconUtils.getIcon('exp_car_insurance'),
        },
        {
          'id': 'exp_car_tax',
          'name': getCategoryName(context, 'exp_car_tax'),
          'icon': IconUtils.getIcon('exp_car_tax'),
        },
        {
          'id': 'exp_car_rental',
          'name': getCategoryName(context, 'exp_car_rental'),
          'icon': IconUtils.getIcon('exp_car_rental'),
        },
      ],
    },
    {
      'id': 'exp_cloth',
      'name': getCategoryName(context, 'exp_cloth'),
      'icon': IconUtils.getIcon('exp_cloth'),
      'color': IconUtils.getColor('exp_cloth'),
      'subModels': [
        {
          'id': 'exp_cloth_daily',
          'name': getCategoryName(context, 'exp_cloth_daily'),
          'icon': IconUtils.getIcon('exp_cloth_daily'),
        },
        {
          'id': 'exp_cloth_shoes',
          'name': getCategoryName(context, 'exp_cloth_shoes'),
          'icon': IconUtils.getIcon('exp_cloth_shoes'),
        },
        {
          'id': 'exp_cloth_acc',
          'name': getCategoryName(context, 'exp_cloth_acc'),
          'icon': IconUtils.getIcon('exp_cloth_acc'),
        },
        {
          'id': 'exp_cloth_tailor',
          'name': getCategoryName(context, 'exp_cloth_tailor'),
          'icon': IconUtils.getIcon('exp_cloth_tailor'),
        },
      ],
    },
    {
      'id': 'exp_beauty',
      'name': getCategoryName(context, 'exp_beauty'),
      'icon': IconUtils.getIcon('exp_beauty'),
      'color': IconUtils.getColor('exp_beauty'),
      'subModels': [
        {
          'id': 'exp_beauty_salon',
          'name': getCategoryName(context, 'exp_beauty_salon'),
          'icon': IconUtils.getIcon('exp_beauty_salon'),
        },
        {
          'id': 'exp_beauty_cosmetics',
          'name': getCategoryName(context, 'exp_beauty_cosmetics'),
          'icon': IconUtils.getIcon('exp_beauty_cosmetics'),
        },
        {
          'id': 'exp_beauty_spa',
          'name': getCategoryName(context, 'exp_beauty_spa'),
          'icon': IconUtils.getIcon('exp_beauty_spa'),
        },
        {
          'id': 'exp_beauty_esthetics',
          'name': getCategoryName(context, 'exp_beauty_esthetics'),
          'icon': IconUtils.getIcon('exp_beauty_esthetics'),
        },
      ],
    },
    {
      'id': 'exp_health',
      'name': getCategoryName(context, 'exp_health'),
      'icon': IconUtils.getIcon('exp_health'),
      'color': IconUtils.getColor('exp_health'),
      'subModels': [
        {
          'id': 'exp_health_doctor',
          'name': getCategoryName(context, 'exp_health_doctor'),
          'icon': IconUtils.getIcon('exp_health_doctor'),
        },
        {
          'id': 'exp_health_medicine',
          'name': getCategoryName(context, 'exp_health_medicine'),
          'icon': IconUtils.getIcon('exp_health_medicine'),
        },
        {
          'id': 'exp_health_dentist',
          'name': getCategoryName(context, 'exp_health_dentist'),
          'icon': IconUtils.getIcon('exp_health_dentist'),
        },
        {
          'id': 'exp_health_surgery',
          'name': getCategoryName(context, 'exp_health_surgery'),
          'icon': IconUtils.getIcon('exp_health_surgery'),
        },
        {
          'id': 'exp_health_optics',
          'name': getCategoryName(context, 'exp_health_optics'),
          'icon': IconUtils.getIcon('exp_health_optics'),
        },
        {
          'id': 'exp_health_veterinary',
          'name': getCategoryName(context, 'exp_health_veterinary'),
          'icon': IconUtils.getIcon('exp_health_veterinary'),
        },
        {
          'id': 'exp_health_therapy',
          'name': getCategoryName(context, 'exp_health_therapy'),
          'icon': IconUtils.getIcon('exp_health_therapy'),
        },
        {
          'id': 'exp_health_supplements',
          'name': getCategoryName(context, 'exp_health_supplements'),
          'icon': IconUtils.getIcon('exp_health_supplements'),
        },
        {
          'id': 'exp_health_insurance',
          'name': getCategoryName(context, 'exp_health_insurance'),
          'icon': IconUtils.getIcon('exp_health_insurance'),
        },
      ],
    },
    {
      'id': 'exp_sub',
      'name': getCategoryName(context, 'exp_sub'),
      'icon': IconUtils.getIcon('exp_sub'),
      'color': IconUtils.getColor('exp_sub'),
      'subModels': [
        {
          'id': 'exp_sub_stream',
          'name': getCategoryName(context, 'exp_sub_stream'),
          'icon': IconUtils.getIcon('exp_sub_stream'),
        },
        {
          'id': 'exp_sub_music',
          'name': getCategoryName(context, 'exp_sub_music'),
          'icon': IconUtils.getIcon('exp_sub_music'),
        },
        {
          'id': 'exp_sub_gym',
          'name': getCategoryName(context, 'exp_sub_gym'),
          'icon': IconUtils.getIcon('exp_sub_gym'),
        },
        {
          'id': 'exp_sub_software',
          'name': getCategoryName(context, 'exp_sub_software'),
          'icon': IconUtils.getIcon('exp_sub_software'),
        },
        {
          'id': 'exp_sub_publishing',
          'name': getCategoryName(context, 'exp_sub_publishing'),
          'icon': IconUtils.getIcon('exp_sub_publishing'),
        },
        {
          'id': 'exp_sub_cloud',
          'name': getCategoryName(context, 'exp_sub_cloud'),
          'icon': IconUtils.getIcon('exp_sub_cloud'),
        },
      ],
    },
    {
      'id': 'exp_fun',
      'name': getCategoryName(context, 'exp_fun'),
      'icon': IconUtils.getIcon('exp_fun'),
      'color': IconUtils.getColor('exp_fun'),
      'subModels': [
        {
          'id': 'exp_fun_cinema',
          'name': getCategoryName(context, 'exp_fun_cinema'),
          'icon': IconUtils.getIcon('exp_fun_cinema'),
        },
        {
          'id': 'exp_fun_concert',
          'name': getCategoryName(context, 'exp_fun_concert'),
          'icon': IconUtils.getIcon('exp_fun_concert'),
        },
        {
          'id': 'exp_fun_event',
          'name': getCategoryName(context, 'exp_fun_event'),
          'icon': IconUtils.getIcon('exp_fun_event'),
        },
        {
          'id': 'exp_fun_game',
          'name': getCategoryName(context, 'exp_fun_game'),
          'icon': IconUtils.getIcon('exp_fun_game'),
        },
        {
          'id': 'exp_fun_hobby',
          'name': getCategoryName(context, 'exp_fun_hobby'),
          'icon': IconUtils.getIcon('exp_fun_hobby'),
        },
        {
          'id': 'exp_fun_gambling',
          'name': getCategoryName(context, 'exp_fun_gambling'),
          'icon': IconUtils.getIcon('exp_fun_gambling'),
        },
      ],
    },
    {
      'id': 'exp_edu',
      'name': getCategoryName(context, 'exp_edu'),
      'icon': IconUtils.getIcon('exp_edu'),
      'color': IconUtils.getColor('exp_edu'),
      'subModels': [
        {
          'id': 'exp_edu_school',
          'name': getCategoryName(context, 'exp_edu_school'),
          'icon': IconUtils.getIcon('exp_edu_school'),
        },
        {
          'id': 'exp_edu_course',
          'name': getCategoryName(context, 'exp_edu_course'),
          'icon': IconUtils.getIcon('exp_edu_course'),
        },
        {
          'id': 'exp_edu_book',
          'name': getCategoryName(context, 'exp_edu_book'),
          'icon': IconUtils.getIcon('exp_edu_book'),
        },
        {
          'id': 'exp_edu_stationery',
          'name': getCategoryName(context, 'exp_edu_stationery'),
          'icon': IconUtils.getIcon('exp_edu_stationery'),
        },
        {
          'id': 'exp_edu_exams',
          'name': getCategoryName(context, 'exp_edu_exams'),
          'icon': IconUtils.getIcon('exp_edu_exams'),
        },
      ],
    },
    {
      'id': 'exp_family',
      'name': getCategoryName(context, 'exp_family'),
      'icon': IconUtils.getIcon('exp_family'),
      'color': IconUtils.getColor('exp_family'),
      'subModels': [
        {
          'id': 'exp_family_baby',
          'name': getCategoryName(context, 'exp_family_baby'),
          'icon': IconUtils.getIcon('exp_family_baby'),
        },
        {
          'id': 'exp_family_toy',
          'name': getCategoryName(context, 'exp_family_toy'),
          'icon': IconUtils.getIcon('exp_family_toy'),
        },
        {
          'id': 'exp_family_allowance',
          'name': getCategoryName(context, 'exp_family_allowance'),
          'icon': IconUtils.getIcon('exp_family_allowance'),
        },
        {
          'id': 'exp_family_daycare',
          'name': getCategoryName(context, 'exp_family_daycare'),
          'icon': IconUtils.getIcon('exp_family_daycare'),
        },
        {
          'id': 'exp_family_support',
          'name': getCategoryName(context, 'exp_family_support'),
          'icon': IconUtils.getIcon('exp_family_support'),
        },
        {
          'id': 'exp_family_care',
          'name': getCategoryName(context, 'exp_family_care'),
          'icon': IconUtils.getIcon('exp_family_care'),
        },
        {
          'id': 'exp_family_alimony',
          'name': getCategoryName(context, 'exp_family_alimony'),
          'icon': IconUtils.getIcon('exp_family_alimony'),
        },
      ],
    },
    {
      'id': 'exp_shopping',
      'name': getCategoryName(context, 'exp_shopping'),
      'icon': IconUtils.getIcon('exp_shopping'),
      'color': IconUtils.getColor('exp_shopping'),
      'subModels': [
        {
          'id': 'exp_shopping_tech',
          'name': getCategoryName(context, 'exp_shopping_tech'),
          'icon': IconUtils.getIcon('exp_shopping_tech'),
        },
        {
          'id': 'exp_shopping_furniture',
          'name': getCategoryName(context, 'exp_shopping_furniture'),
          'icon': IconUtils.getIcon('exp_shopping_furniture'),
        },
        {
          'id': 'exp_shopping_decor',
          'name': getCategoryName(context, 'exp_shopping_decor'),
          'icon': IconUtils.getIcon('exp_shopping_decor'),
        },
        {
          'id': 'exp_shopping_kitchen',
          'name': getCategoryName(context, 'exp_shopping_kitchen'),
          'icon': IconUtils.getIcon('exp_shopping_kitchen'),
        },
        {
          'id': 'exp_shopping_gift',
          'name': getCategoryName(context, 'exp_shopping_gift'),
          'icon': IconUtils.getIcon('exp_shopping_gift'),
        },
        {
          'id': 'exp_shopping_general',
          'name': getCategoryName(context, 'exp_shopping_general'),
          'icon': IconUtils.getIcon('exp_shopping_general'),
        },
        {
          'id': 'exp_shopping_sports',
          'name': getCategoryName(context, 'exp_shopping_sports'),
          'icon': IconUtils.getIcon('exp_shopping_sports'),
        },
        {
          'id': 'exp_shopping_shipping',
          'name': getCategoryName(context, 'exp_shopping_shipping'),
          'icon': IconUtils.getIcon('exp_shopping_shipping'),
        },
      ],
    },
    {
      'id': 'exp_travel',
      'name': getCategoryName(context, 'exp_travel'),
      'icon': IconUtils.getIcon('exp_travel'),
      'color': IconUtils.getColor('exp_travel'),
      'subModels': [
        {
          'id': 'exp_travel_hotel',
          'name': getCategoryName(context, 'exp_travel_hotel'),
          'icon': IconUtils.getIcon('exp_travel_hotel'),
        },
        {
          'id': 'exp_travel_flight',
          'name': getCategoryName(context, 'exp_travel_flight'),
          'icon': IconUtils.getIcon('exp_travel_flight'),
        },
        {
          'id': 'exp_travel_tour',
          'name': getCategoryName(context, 'exp_travel_tour'),
          'icon': IconUtils.getIcon('exp_travel_tour'),
        },
        {
          'id': 'exp_travel_visa',
          'name': getCategoryName(context, 'exp_travel_visa'),
          'icon': IconUtils.getIcon('exp_travel_visa'),
        },
      ],
    },
    {
      'id': 'exp_debt',
      'name': getCategoryName(context, 'exp_debt'),
      'icon': IconUtils.getIcon('exp_debt'),
      'color': IconUtils.getColor('exp_debt'),
      'subModels': [
        {
          'id': 'exp_debt_credit_card',
          'name': getCategoryName(context, 'exp_debt_credit_card'),
          'icon': IconUtils.getIcon('exp_debt_credit_card'),
        },
        {
          'id': 'exp_debt_loan',
          'name': getCategoryName(context, 'exp_debt_loan'),
          'icon': IconUtils.getIcon('exp_debt_loan'),
        },
        {
          'id': 'exp_debt_personal',
          'name': getCategoryName(context, 'exp_debt_personal'),
          'icon': IconUtils.getIcon('exp_debt_personal'),
        },
        {
          'id': 'exp_debt_lending',
          'name': getCategoryName(context, 'exp_debt_lending'),
          'icon': IconUtils.getIcon('exp_debt_lending'),
        },
      ],
    },
    {
      'id': 'exp_invest',
      'name': getCategoryName(context, 'exp_invest'),
      'icon': IconUtils.getIcon('exp_invest'),
      'color': IconUtils.getColor('exp_invest'),
      'subModels': [
        {
          'id': 'exp_invest_stocks',
          'name': getCategoryName(context, 'exp_invest_stocks'),
          'icon': IconUtils.getIcon('exp_invest_stocks'),
        },
        {
          'id': 'exp_invest_gold',
          'name': getCategoryName(context, 'exp_invest_gold'),
          'icon': IconUtils.getIcon('exp_invest_gold'),
        },
        {
          'id': 'exp_invest_crypto',
          'name': getCategoryName(context, 'exp_invest_crypto'),
          'icon': IconUtils.getIcon('exp_invest_crypto'),
        },
        {
          'id': 'exp_invest_pension',
          'name': getCategoryName(context, 'exp_invest_pension'),
          'icon': IconUtils.getIcon('exp_invest_pension'),
        },
      ],
    },
    {
      'id': 'exp_tax',
      'name': getCategoryName(context, 'exp_tax'),
      'icon': IconUtils.getIcon('exp_tax'),
      'color': IconUtils.getColor('exp_tax'),
      'subModels': [
        {
          'id': 'exp_tax_income',
          'name': getCategoryName(context, 'exp_tax_income'),
          'icon': IconUtils.getIcon('exp_tax_income'),
        },
        {
          'id': 'exp_tax_fine',
          'name': getCategoryName(context, 'exp_tax_fine'),
          'icon': IconUtils.getIcon('exp_tax_fine'),
        },
        {
          'id': 'exp_tax_fee',
          'name': getCategoryName(context, 'exp_tax_fee'),
          'icon': IconUtils.getIcon('exp_tax_fee'),
        },
      ],
    },
    {
      'id': 'exp_other',
      'name': getCategoryName(context, 'exp_other'),
      'icon': IconUtils.getIcon('exp_other'),
      'color': IconUtils.getColor('exp_other'),
      'subModels': [
        {
          'id': 'exp_other_general',
          'name': getCategoryName(context, 'exp_other_general'),
          'icon': IconUtils.getIcon('exp_other_general'),
        },
        {
          'id': 'exp_other_donation',
          'name': getCategoryName(context, 'exp_other_donation'),
          'icon': IconUtils.getIcon('exp_other_donation'),
        },
        {
          'id': 'exp_other_tip',
          'name': getCategoryName(context, 'exp_other_tip'),
          'icon': IconUtils.getIcon('exp_other_tip'),
        },
        {
          'id': 'exp_other_bank_fee',
          'name': getCategoryName(context, 'exp_other_bank_fee'),
          'icon': IconUtils.getIcon('exp_other_bank_fee'),
        },
      ],
    },
  ];

  static List<Map<String, dynamic>> getIncomeCategories(BuildContext context, AppLocalizations l10n) => [
    {
      'id': 'inc_salary',
      'name': getCategoryName(context, 'inc_salary'),
      'icon': IconUtils.getIcon('inc_salary'),
      'color': IconUtils.getColor('inc_salary'),
      'subModels': [
        {
          'id': 'inc_salary_main',
          'name': getCategoryName(context, 'inc_salary_main'),
          'icon': IconUtils.getIcon('inc_salary_main'),
        },
        {
          'id': 'inc_salary_bonus',
          'name': getCategoryName(context, 'inc_salary_bonus'),
          'icon': IconUtils.getIcon('inc_salary_bonus'),
        },
        {
          'id': 'inc_salary_dividend',
          'name': getCategoryName(context, 'inc_salary_dividend'),
          'icon': IconUtils.getIcon('inc_salary_dividend'),
        },
        {
          'id': 'inc_salary_pension',
          'name': getCategoryName(context, 'inc_salary_pension'),
          'icon': IconUtils.getIcon('inc_salary_pension'),
        },
        {
          'id': 'inc_salary_severance',
          'name': getCategoryName(context, 'inc_salary_severance'),
          'icon': IconUtils.getIcon('inc_salary_severance'),
        },
      ],
    },
    {
      'id': 'inc_extra',
      'name': getCategoryName(context, 'inc_extra'),
      'icon': IconUtils.getIcon('inc_extra'),
      'color': IconUtils.getColor('inc_extra'),
      'subModels': [
        {
          'id': 'inc_extra_freelance',
          'name': getCategoryName(context, 'inc_extra_freelance'),
          'icon': IconUtils.getIcon('inc_extra_freelance'),
        },
        {
          'id': 'inc_extra_parttime',
          'name': getCategoryName(context, 'inc_extra_parttime'),
          'icon': IconUtils.getIcon('inc_extra_parttime'),
        },
        {
          'id': 'inc_extra_commission',
          'name': getCategoryName(context, 'inc_extra_commission'),
          'icon': IconUtils.getIcon('inc_extra_commission'),
        },
        {
          'id': 'inc_extra_content',
          'name': getCategoryName(context, 'inc_extra_content'),
          'icon': IconUtils.getIcon('inc_extra_content'),
        },
        {
          'id': 'inc_extra_affiliate',
          'name': getCategoryName(context, 'inc_extra_affiliate'),
          'icon': IconUtils.getIcon('inc_extra_affiliate'),
        },
      ],
    },
    {
      'id': 'inc_invest',
      'name': getCategoryName(context, 'inc_invest'),
      'icon': IconUtils.getIcon('inc_invest'),
      'color': IconUtils.getColor('inc_invest'),
      'subModels': [
        {
          'id': 'inc_invest_stock',
          'name': getCategoryName(context, 'inc_invest_stock'),
          'icon': IconUtils.getIcon('inc_invest_stock'),
        },
        {
          'id': 'inc_invest_crypto',
          'name': getCategoryName(context, 'inc_invest_crypto'),
          'icon': IconUtils.getIcon('inc_invest_crypto'),
        },
        {
          'id': 'inc_invest_interest',
          'name': getCategoryName(context, 'inc_invest_interest'),
          'icon': IconUtils.getIcon('inc_invest_interest'),
        },
        {
          'id': 'inc_invest_gold',
          'name': getCategoryName(context, 'inc_invest_gold'),
          'icon': IconUtils.getIcon('inc_invest_gold'),
        },
        {
          'id': 'inc_invest_forex',
          'name': getCategoryName(context, 'inc_invest_forex'),
          'icon': IconUtils.getIcon('inc_invest_forex'),
        },
        {
          'id': 'inc_invest_bond',
          'name': getCategoryName(context, 'inc_invest_bond'),
          'icon': IconUtils.getIcon('inc_invest_bond'),
        },
      ],
    },
    {
      'id': 'inc_rent',
      'name': getCategoryName(context, 'inc_rent'),
      'icon': IconUtils.getIcon('inc_rent'),
      'color': IconUtils.getColor('inc_rent'),
      'subModels': [
        {
          'id': 'inc_rent_home',
          'name': getCategoryName(context, 'inc_rent_home'),
          'icon': IconUtils.getIcon('inc_rent_home'),
        },
        {
          'id': 'inc_rent_office',
          'name': getCategoryName(context, 'inc_rent_office'),
          'icon': IconUtils.getIcon('inc_rent_office'),
        },
        {
          'id': 'inc_rent_car',
          'name': getCategoryName(context, 'inc_rent_car'),
          'icon': IconUtils.getIcon('inc_rent_car'),
        },
        {
          'id': 'inc_rent_equipment',
          'name': getCategoryName(context, 'inc_rent_equipment'),
          'icon': IconUtils.getIcon('inc_rent_equipment'),
        },
      ],
    },
    {
      'id': 'inc_scholarship',
      'name': getCategoryName(context, 'inc_scholarship'),
      'icon': IconUtils.getIcon('inc_scholarship'),
      'color': IconUtils.getColor('inc_scholarship'),
      'subModels': [
        {
          'id': 'inc_scholarship_award',
          'name': getCategoryName(context, 'inc_scholarship_award'),
          'icon': IconUtils.getIcon('inc_scholarship_award'),
        },
        {
          'id': 'inc_scholarship_loan',
          'name': getCategoryName(context, 'inc_scholarship_loan'),
          'icon': IconUtils.getIcon('inc_scholarship_loan'),
        },
        {
          'id': 'inc_scholarship_gov',
          'name': getCategoryName(context, 'inc_scholarship_gov'),
          'icon': IconUtils.getIcon('inc_scholarship_gov'),
        },
        {
          'id': 'inc_scholarship_grant',
          'name': getCategoryName(context, 'inc_scholarship_grant'),
          'icon': IconUtils.getIcon('inc_scholarship_grant'),
        },
      ],
    },
    {
      'id': 'inc_sale',
      'name': getCategoryName(context, 'inc_sale'),
      'icon': IconUtils.getIcon('inc_sale'),
      'color': IconUtils.getColor('inc_sale'),
      'subModels': [
        {
          'id': 'inc_sale_online',
          'name': getCategoryName(context, 'inc_sale_online'),
          'icon': IconUtils.getIcon('inc_sale_online'),
        },
        {
          'id': 'inc_sale_physical',
          'name': getCategoryName(context, 'inc_sale_physical'),
          'icon': IconUtils.getIcon('inc_sale_physical'),
        },
        {
          'id': 'inc_sale_vehicle',
          'name': getCategoryName(context, 'inc_sale_vehicle'),
          'icon': IconUtils.getIcon('inc_sale_vehicle'),
        },
        {
          'id': 'inc_sale_property',
          'name': getCategoryName(context, 'inc_sale_property'),
          'icon': IconUtils.getIcon('inc_sale_property'),
        },
      ],
    },
    {
      'id': 'inc_gift',
      'name': getCategoryName(context, 'inc_gift'),
      'icon': IconUtils.getIcon('inc_gift'),
      'color': IconUtils.getColor('inc_gift'),
      'subModels': [
        {
          'id': 'inc_gift_general',
          'name': getCategoryName(context, 'inc_gift_general'),
          'icon': IconUtils.getIcon('inc_gift_general'),
        },
        {
          'id': 'inc_gift_award',
          'name': getCategoryName(context, 'inc_gift_award'),
          'icon': IconUtils.getIcon('inc_gift_award'),
        },
        {
          'id': 'inc_gift_inheritance',
          'name': getCategoryName(context, 'inc_gift_inheritance'),
          'icon': IconUtils.getIcon('inc_gift_inheritance'),
        },
        {
          'id': 'inc_gift_alimony',
          'name': getCategoryName(context, 'inc_gift_alimony'),
          'icon': IconUtils.getIcon('inc_gift_alimony'),
        },
        {
          'id': 'inc_gift_allowance',
          'name': getCategoryName(context, 'inc_gift_allowance'),
          'icon': IconUtils.getIcon('inc_gift_allowance'),
        },
      ],
    },
    {
      'id': 'inc_other',
      'name': getCategoryName(context, 'inc_other'),
      'icon': IconUtils.getIcon('inc_other'),
      'color': IconUtils.getColor('inc_other'),
      'subModels': [
        {
          'id': 'inc_other_general',
          'name': getCategoryName(context, 'inc_other_general'),
          'icon': IconUtils.getIcon('inc_other_general'),
        },
        {
          'id': 'inc_other_refund',
          'name': getCategoryName(context, 'inc_other_refund'),
          'icon': IconUtils.getIcon('inc_other_refund'),
        },
        {
          'id': 'inc_other_lottery',
          'name': getCategoryName(context, 'inc_other_lottery'),
          'icon': IconUtils.getIcon('inc_other_lottery'),
        },
        {
          'id': 'inc_other_collection',
          'name': getCategoryName(context, 'inc_other_collection'),
          'icon': IconUtils.getIcon('inc_other_collection'),
        },
        {
          'id': 'inc_other_cashback',
          'name': getCategoryName(context, 'inc_other_cashback'),
          'icon': IconUtils.getIcon('inc_other_cashback'),
        },
        {
          'id': 'inc_other_tax_refund',
          'name': getCategoryName(context, 'inc_other_tax_refund'),
          'icon': IconUtils.getIcon('inc_other_tax_refund'),
        },
      ],
    },
  ];
}
